
DELIMITER //

CREATE OR REPLACE PROCEDURE SP_REPROCESO_VARIACION_DIARIA_FINAL(
    P_FECHA_INICIO DATE,
    P_FECHA_FIN DATE
)
AS
DECLARE
    V_FECHA DATE;
BEGIN

    V_FECHA = P_FECHA_INICIO;

    WHILE V_FECHA <= P_FECHA_FIN LOOP

        CALL SP_CREAR_VARIACION_CONTABLE_FINAL(
            4,
            V_FECHA
        );

        V_FECHA = DATE_ADD(V_FECHA, INTERVAL 1 DAY);

    END LOOP;

END //

DELIMITER ;

-- 
CALL SP_REPROCESO_VARIACION_DIARIA_FINAL(
'2026-01-01',
'2026-01-31'
);
