-- Propuesta optimizada para BDS.sp_cargar_saldos_operativos_hb.
-- Ajustar tipos/DDL final segun la definicion real de las tablas BDS.

DELIMITER //

CREATE OR REPLACE PROCEDURE BDS.sp_cargar_saldos_operativos_hb(
    IN p_fecha_proceso DATE,
    IN p_dias INT
)
AS
BEGIN
    DECLARE v_fecha_inicio DATE;
    DECLARE v_fecha_inicio_mes DATE;
    DECLARE v_fecha_fin DATE;

    SELECT
        MAX(C.FEC_CALENDARIO),
        DATE_FORMAT(p_fecha_proceso, '%Y-%m-01'),
        p_fecha_proceso
    INTO
        v_fecha_inicio,
        v_fecha_inicio_mes,
        v_fecha_fin
    FROM BDS_CALENDARIOS C
    WHERE C.COD_CALENDARIO = 1
      AND C.IND_DIA_HABIL = 'S'
      AND C.FEC_CALENDARIO <= DATE_SUB(p_fecha_proceso, INTERVAL p_dias DAY);

    DROP TEMPORARY TABLE IF EXISTS tmp_calendario_global;
    CREATE TEMPORARY TABLE tmp_calendario_global AS
    WITH rango AS (
        SELECT
            DATE_FORMAT(v_fecha_inicio, '%Y-%m-01') AS fecha_inicio,
            v_fecha_fin AS fecha_fin
    )
    SELECT
        cal.FEC_CALENDARIO AS FECHA_PROCESO,
        cal.IND_DIA_HABIL,
        MAX(hab.FEC_CALENDARIO) AS FECHA_ORIGEN
    FROM BDS_CALENDARIOS cal
    JOIN rango r
      ON cal.FEC_CALENDARIO BETWEEN r.fecha_inicio AND r.fecha_fin
    JOIN BDS_CALENDARIOS hab
      ON hab.COD_CALENDARIO = cal.COD_CALENDARIO
     AND hab.IND_DIA_HABIL = 'S'
     AND hab.FEC_CALENDARIO <= cal.FEC_CALENDARIO
    WHERE cal.COD_CALENDARIO = 1
    GROUP BY cal.FEC_CALENDARIO, cal.IND_DIA_HABIL;

    DROP TEMPORARY TABLE IF EXISTS tmp_base_rango;
    CREATE TEMPORARY TABLE tmp_base_rango AS
    SELECT
        CONCAT(
            s.COD_EMPRESA, '|',
            s.COD_MODULO, '|',
            s.COD_SUCURSAL, '|',
            s.COD_MONEDA, '|',
            s.COD_PAPEL, '|',
            s.NUM_CUENTA_BT, '|',
            s.COD_OPERACION, '|',
            s.COD_SUB_OPERACION, '|',
            s.COD_TIPO_OPERACION
        ) AS ID_OPERACION_CIERRE,
        c.FECHA_PROCESO,
        s.COD_EMPRESA,
        s.COD_SUCURSAL,
        s.COD_RUBRO,
        s.COD_MONEDA,
        s.COD_PAPEL,
        s.NUM_CUENTA_BT,
        s.COD_OPERACION,
        s.COD_SUB_OPERACION,
        s.COD_TIPO_OPERACION,
        s.COD_MODULO,
        s.FEC_VENCIMIENTO,
        s.FEC_VALOR,
        s.IND_CATEGORIA_RIESGO,
        s.COD_ACTI_BCO_CENTRAL,
        s.COD_PRODUCTO,
        s.MTO_SALDO_ORIGEN,
        s.MTO_SALDO_MN,
        s.MTO_SALDO_ME,
        s.MTO_SALDO_MO,
        s.MTO_INTERES,
        s.MTO_PREVISIONES,
        c.IND_DIA_HABIL,
        CASE
            WHEN c.FECHA_PROCESO = c.FECHA_ORIGEN THEN 'ORIGINAL'
            ELSE 'COPIA_HABIL'
        END AS TIPO_ORIGEN,
        s.FUENTE,
        s.FECHA_CARGA,
        s.BATCH_ID
    FROM tmp_calendario_global c
    JOIN BDS_SALDOS_CIERRE s
      ON s.FECHA_PROCESO = c.FECHA_ORIGEN
    WHERE s.FECHA_PROCESO BETWEEN v_fecha_inicio AND v_fecha_fin;

    DROP TEMPORARY TABLE IF EXISTS tmp_base_deduplicada;
    CREATE TEMPORARY TABLE tmp_base_deduplicada AS
    WITH ranked AS (
        SELECT
            b.*,
            ROW_NUMBER() OVER (
                PARTITION BY
                    b.ID_OPERACION_CIERRE,
                    b.FECHA_PROCESO,
                    b.COD_RUBRO
                ORDER BY
                    CASE WHEN b.TIPO_ORIGEN = 'ORIGINAL' THEN 0 ELSE 1 END,
                    CASE
                        WHEN COALESCE(b.MTO_SALDO_ORIGEN, 0) <> 0
                          OR COALESCE(b.MTO_SALDO_MN, 0) <> 0
                          OR COALESCE(b.MTO_SALDO_ME, 0) <> 0
                          OR COALESCE(b.MTO_SALDO_MO, 0) <> 0
                        THEN 0 ELSE 1
                    END,
                    b.FECHA_CARGA DESC,
                    b.BATCH_ID DESC
            ) AS rn
        FROM tmp_base_rango b
    )
    SELECT
        ID_OPERACION_CIERRE,
        FECHA_PROCESO,
        COD_EMPRESA,
        COD_SUCURSAL,
        COD_RUBRO,
        COD_MONEDA,
        COD_PAPEL,
        NUM_CUENTA_BT,
        COD_OPERACION,
        COD_SUB_OPERACION,
        COD_TIPO_OPERACION,
        COD_MODULO,
        FEC_VENCIMIENTO,
        FEC_VALOR,
        IND_CATEGORIA_RIESGO,
        COD_ACTI_BCO_CENTRAL,
        COD_PRODUCTO,
        MTO_SALDO_ORIGEN,
        MTO_SALDO_MN,
        MTO_SALDO_ME,
        MTO_SALDO_MO,
        MTO_INTERES,
        MTO_PREVISIONES,
        IND_DIA_HABIL,
        TIPO_ORIGEN,
        FUENTE,
        FECHA_CARGA,
        BATCH_ID
    FROM ranked
    WHERE rn = 1;

    DROP TEMPORARY TABLE IF EXISTS tmp_operaciones_enriquecidas;
    CREATE TEMPORARY TABLE tmp_operaciones_enriquecidas AS
    WITH base AS (
        SELECT
            b.*,
            CASE WHEN b.COD_MODULO IN (20, 120, 321, 22, 185, 184, 162, 155, 21)
                 THEN 'PASIVO'
                 ELSE 'ACTIVO'
            END AS TIPO_CARTERA
        FROM tmp_base_deduplicada b
    )
    SELECT
        ID_OPERACION_CIERRE,
        FECHA_PROCESO,
        COD_EMPRESA,
        COD_SUCURSAL,
        COD_RUBRO,
        COD_MONEDA,
        COD_PAPEL,
        NUM_CUENTA_BT,
        COD_OPERACION,
        COD_SUB_OPERACION,
        COD_TIPO_OPERACION,
        COD_MODULO,
        FEC_VENCIMIENTO,
        FEC_VALOR,
        IND_CATEGORIA_RIESGO,
        COD_ACTI_BCO_CENTRAL,
        COD_PRODUCTO,
        MTO_SALDO_ORIGEN,
        MTO_SALDO_MN,
        MTO_SALDO_ME,
        MTO_SALDO_MO,
        MTO_INTERES,
        MTO_PREVISIONES,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1401', '1411', '1421')
             THEN MTO_SALDO_MO ELSE 0 END AS MTO_SALDO_VIGENTE_MO,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1403', '1413', '1423')
             THEN MTO_SALDO_MO ELSE 0 END AS MTO_SALDO_RESTRUCTURADO_MO,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1404', '1414', '1424')
             THEN MTO_SALDO_MO ELSE 0 END AS MTO_SALDO_REFINANCIADO_MO,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1405', '1415', '1425')
             THEN MTO_SALDO_MO ELSE 0 END AS MTO_SALDO_VENCIDO_MO,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1406', '1416', '1426')
             THEN MTO_SALDO_MO ELSE 0 END AS MTO_SALDO_JUDIAL_MO,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1401', '1411', '1421')
             THEN MTO_SALDO_MN ELSE 0 END AS MTO_SALDO_VIGENTE_MN,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1403', '1413', '1423')
             THEN MTO_SALDO_MN ELSE 0 END AS MTO_SALDO_RESTRUCTURADO_MN,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1404', '1414', '1424')
             THEN MTO_SALDO_MN ELSE 0 END AS MTO_SALDO_REFINANCIADO_MN,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1405', '1415', '1425')
             THEN MTO_SALDO_MN ELSE 0 END AS MTO_SALDO_VENCIDO_MN,
        CASE WHEN TIPO_CARTERA = 'ACTIVO' AND LEFT(COD_RUBRO, 4) IN ('1406', '1416', '1426')
             THEN MTO_SALDO_MN ELSE 0 END AS MTO_SALDO_JUDIAL_MN,
        IND_DIA_HABIL,
        FUENTE,
        FECHA_CARGA,
        BATCH_ID
    FROM base;

    DROP TEMPORARY TABLE IF EXISTS tmp_operaciones_dia;
    CREATE TEMPORARY TABLE tmp_operaciones_dia AS
    SELECT
        ID_OPERACION_CIERRE,
        FECHA_PROCESO,
        DAY(FECHA_PROCESO) AS NUM_DIA_MES,
        DAY(LAST_DAY(FECHA_PROCESO)) AS TOTAL_DIAS_MES,
        MAX(COD_EMPRESA) AS COD_EMPRESA,
        MAX(COD_SUCURSAL) AS COD_SUCURSAL,
        MAX(COD_MONEDA) AS COD_MONEDA,
        MAX(COD_PAPEL) AS COD_PAPEL,
        MAX(NUM_CUENTA_BT) AS NUM_CUENTA_BT,
        MAX(COD_OPERACION) AS COD_OPERACION,
        MAX(COD_SUB_OPERACION) AS COD_SUB_OPERACION,
        MAX(COD_TIPO_OPERACION) AS COD_TIPO_OPERACION,
        MAX(COD_MODULO) AS COD_MODULO,
        MAX(FEC_VENCIMIENTO) AS FEC_VENCIMIENTO,
        MAX(FEC_VALOR) AS FEC_VALOR,
        MAX(IND_CATEGORIA_RIESGO) AS IND_CATEGORIA_RIESGO,
        MAX(COD_ACTI_BCO_CENTRAL) AS COD_ACTI_BCO_CENTRAL,
        SUM(MTO_SALDO_ORIGEN) AS TOTAL_DIA_SALDO_ORIGEN,
        SUM(MTO_SALDO_MN) AS TOTAL_DIA_SALDO_MN,
        SUM(MTO_SALDO_ME) AS TOTAL_DIA_SALDO_ME,
        SUM(MTO_SALDO_MO) AS TOTAL_DIA_SALDO_MO,
        SUM(MTO_INTERES) AS TOTAL_DIA_INTERES,
        SUM(MTO_PREVISIONES) AS TOTAL_DIA_PREVISIONES,
        SUM(MTO_SALDO_VIGENTE_MO) AS TOTAL_DIA_SALDO_VIGENTE_MO,
        SUM(MTO_SALDO_RESTRUCTURADO_MO) AS TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
        SUM(MTO_SALDO_REFINANCIADO_MO) AS TOTAL_DIA_SALDO_REFINANCIADO_MO,
        SUM(MTO_SALDO_VENCIDO_MO) AS TOTAL_DIA_SALDO_VENCIDO_MO,
        SUM(MTO_SALDO_JUDIAL_MO) AS TOTAL_DIA_SALDO_JUDIAL_MO,
        SUM(MTO_SALDO_VIGENTE_MN) AS TOTAL_DIA_SALDO_VIGENTE_MN,
        SUM(MTO_SALDO_RESTRUCTURADO_MN) AS TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
        SUM(MTO_SALDO_REFINANCIADO_MN) AS TOTAL_DIA_SALDO_REFINANCIADO_MN,
        SUM(MTO_SALDO_VENCIDO_MN) AS TOTAL_DIA_SALDO_VENCIDO_MN,
        SUM(MTO_SALDO_JUDIAL_MN) AS TOTAL_DIA_SALDO_JUDIAL_MN,
        MAX(FUENTE) AS FUENTE,
        MAX(IND_DIA_HABIL) AS IND_DIA_HABIL,
        MAX(FECHA_CARGA) AS FECHA_CARGA,
        MAX(BATCH_ID) AS BATCH_ID
    FROM tmp_operaciones_enriquecidas
    GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO;

    DELETE FROM BDS_SALDOS_OPERATIVOS_HB
    WHERE FECHA_PROCESO BETWEEN v_fecha_inicio_mes AND v_fecha_fin;

    INSERT INTO BDS_SALDOS_OPERATIVOS_HB (
        ID_OPERACION_CIERRE,
        FECHA_PROCESO,
        COD_EMPRESA,
        COD_SUCURSAL,
        COD_MONEDA,
        COD_PAPEL,
        NUM_CUENTA_BT,
        COD_OPERACION,
        COD_SUB_OPERACION,
        COD_TIPO_OPERACION,
        COD_MODULO,
        FEC_VENCIMIENTO,
        FEC_VALOR,
        IND_CATEGORIA_RIESGO,
        COD_ACTI_BCO_CENTRAL,
        TOTAL_DIAS_MES,
        TOTAL_DIA_SALDO_ORIGEN,
        TOTAL_DIA_SALDO_MN,
        TOTAL_DIA_SALDO_ME,
        TOTAL_DIA_SALDO_MO,
        TOTAL_DIA_INTERES,
        TOTAL_DIA_PREVISIONES,
        TOTAL_DIA_SALDO_VIGENTE_MO,
        TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
        TOTAL_DIA_SALDO_REFINANCIADO_MO,
        TOTAL_DIA_SALDO_VENCIDO_MO,
        TOTAL_DIA_SALDO_JUDIAL_MO,
        TOTAL_DIA_SALDO_VIGENTE_MN,
        TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
        TOTAL_DIA_SALDO_REFINANCIADO_MN,
        TOTAL_DIA_SALDO_VENCIDO_MN,
        TOTAL_DIA_SALDO_JUDIAL_MN,
        AVG_SALDO_ORIGEN,
        AVG_SALDO_MN,
        AVG_SALDO_ME,
        AVG_SALDO_MO,
        AVG_INTERES,
        AVG_PREVISIONES,
        AVG_SALDO_VIGENTE_MO,
        AVG_SALDO_RESTRUCTURADO_MO,
        AVG_SALDO_REFINANCIADO_MO,
        AVG_SALDO_VENCIDO_MO,
        AVG_SALDO_JUDIAL_MO,
        AVG_SALDO_VIGENTE_MN,
        AVG_SALDO_RESTRUCTURADO_MN,
        AVG_SALDO_REFINANCIADO_MN,
        AVG_SALDO_VENCIDO_MN,
        AVG_SALDO_JUDIAL_MN,
        FUENTE,
        IND_DIA_HABIL,
        FECHA_CARGA,
        BATCH_ID
    )
    SELECT
        ID_OPERACION_CIERRE,
        FECHA_PROCESO,
        COD_EMPRESA,
        COD_SUCURSAL,
        COD_MONEDA,
        COD_PAPEL,
        NUM_CUENTA_BT,
        COD_OPERACION,
        COD_SUB_OPERACION,
        COD_TIPO_OPERACION,
        COD_MODULO,
        FEC_VENCIMIENTO,
        FEC_VALOR,
        IND_CATEGORIA_RIESGO,
        COD_ACTI_BCO_CENTRAL,
        TOTAL_DIAS_MES,
        TOTAL_DIA_SALDO_ORIGEN,
        TOTAL_DIA_SALDO_MN,
        TOTAL_DIA_SALDO_ME,
        TOTAL_DIA_SALDO_MO,
        TOTAL_DIA_INTERES,
        TOTAL_DIA_PREVISIONES,
        TOTAL_DIA_SALDO_VIGENTE_MO,
        TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
        TOTAL_DIA_SALDO_REFINANCIADO_MO,
        TOTAL_DIA_SALDO_VENCIDO_MO,
        TOTAL_DIA_SALDO_JUDIAL_MO,
        TOTAL_DIA_SALDO_VIGENTE_MN,
        TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
        TOTAL_DIA_SALDO_REFINANCIADO_MN,
        TOTAL_DIA_SALDO_VENCIDO_MN,
        TOTAL_DIA_SALDO_JUDIAL_MN,
        CAST(SUM(TOTAL_DIA_SALDO_ORIGEN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_MN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_ME) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_MO) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_INTERES) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_PREVISIONES) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_VIGENTE_MO) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_RESTRUCTURADO_MO) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_REFINANCIADO_MO) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_VENCIDO_MO) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_JUDIAL_MO) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_VIGENTE_MN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_RESTRUCTURADO_MN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_REFINANCIADO_MN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_VENCIDO_MN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        CAST(SUM(TOTAL_DIA_SALDO_JUDIAL_MN) OVER w / NUM_DIA_MES AS DECIMAL(18, 4)),
        FUENTE,
        IND_DIA_HABIL,
        FECHA_CARGA,
        BATCH_ID
    FROM tmp_operaciones_dia
    WHERE FECHA_PROCESO BETWEEN v_fecha_inicio_mes AND v_fecha_fin
    WINDOW w AS (
        PARTITION BY ID_OPERACION_CIERRE, YEAR(FECHA_PROCESO), MONTH(FECHA_PROCESO)
        ORDER BY FECHA_PROCESO
    );

    IF EXISTS (
        SELECT 1
        FROM BDS_SALDOS_OPERATIVOS_HB
        WHERE FECHA_PROCESO BETWEEN v_fecha_inicio_mes AND v_fecha_fin
        GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO
        HAVING COUNT(*) > 1
        LIMIT 1
    ) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Control duplicados fallo: BDS_SALDOS_OPERATIVOS_HB tiene mas de una fila por ID_OPERACION_CIERRE y FECHA_PROCESO';
    END IF;
END //

DELIMITER ;
