SET @v_fecha_proceso ='2026-04-01'
SET @p_dias = 31


drop table PARAMETROS_TABLA
CREATE TABLE PARAMETROS_TABLA AS
	WITH PARAMETROS AS
	(
		SELECT
			CAST(@v_fecha_proceso AS DATE) AS FECHA_PROCESO,
			@p_dias AS NUM_DIAS
	),

	FECHA_RESTADA AS
	(
		SELECT
			FECHA_PROCESO,
			DATE_SUB(FECHA_PROCESO, INTERVAL NUM_DIAS DAY) AS FECHA_CALCULADA
		FROM PARAMETROS
	),

	FECHA_HABIL_BASE AS
	(
		SELECT
			MAX(C.FEC_CALENDARIO) AS FECHA_INICIO
		FROM FECHA_RESTADA F
		JOIN BDS_CALENDARIOS C
			ON C.COD_CALENDARIO = 1
		AND C.IND_DIA_HABIL = 'S'
		AND C.FEC_CALENDARIO <= F.FECHA_CALCULADA
	),

	INICIO_MES AS
	(
		SELECT
			DATE_FORMAT(FECHA_CALCULADA,'%Y-%m-01') AS FECHA_INICIO_MES
		FROM FECHA_RESTADA
	)

	SELECT
		P.FECHA_PROCESO AS FECHA_FIN,
		I.FECHA_INICIO_MES,
		H.FECHA_INICIO
	FROM PARAMETROS P
	CROSS JOIN INICIO_MES I
	CROSS JOIN FECHA_HABIL_BASE H;
	
	
SELECT * FROM PARAMETROS_TABLA

	SET @v_fecha_inicio=''
	SET @v_fecha_fin =''
	SET @v_fecha_inicio_mes = ''
	SELECT  FECHA_INICIO INTO @v_fecha_inicio   FROM PARAMETROS_TABLA;
	SELECT  FECHA_FIN INTO @v_fecha_fin   FROM PARAMETROS_TABLA;
	SELECT  FECHA_INICIO_MES INTO @v_fecha_inicio_mes FROM PARAMETROS_TABLA;
	
	SELECT * FROM PARAMETROS_TABLA
	-- DELETE FROM BDS_SALDOS_OPERATIVOS_HB WHERE FECHA_PROCESO >= @v_fecha_inicio_mes AND FECHA_PROCESO <= @v_fecha_fin;
	
	
---------------------------------------------------------------------------------------------------------------
	DROP TABLE TEMP_BASE_INICIAL
	
		CREATE TABLE TEMP_BASE_INICIAL AS 
		WITH  BASE_TEMPORAL  AS (
			SELECT  MONTH(FECHA_PROCESO) AS MES,
				YEAR(FECHA_PROCESO) AS ANIO, * 
		FROM BDS_SALDOS_CIERRE
			WHERE FECHA_PROCESO>=@v_fecha_inicio
			AND FECHA_PROCESO <= @v_fecha_fin
		)
		SELECT * FROM BASE_TEMPORAL;
		
		select * from TEMP_BASE_INICIAL
		
--
DROP TABLE TEMP_BASE_COMPLETA_POR_MES
	CREATE TABLE TEMP_BASE_COMPLETA_POR_MES AS 
	WITH tabla_base AS (
		SELECT
			DATE_ADD(
				LAST_DAY(DATE_SUB(MIN(FECHA_PROCESO), INTERVAL 1 MONTH)),
				INTERVAL 1 DAY
			) AS INICIO_FECHA,
			MAX(FECHA_PROCESO) AS FIN_FECHA
		FROM TEMP_BASE_INICIAL
	),

	TEMP_BASE_COMPLETA_POR_MES AS (
		SELECT
			*
		FROM TEMP_BASE_INICIAL bho
		WHERE bho.FECHA_PROCESO BETWEEN
			(SELECT INICIO_FECHA FROM tabla_base)
			AND
			(SELECT FIN_FECHA FROM tabla_base)
	)
	SELECT * FROM TEMP_BASE_COMPLETA_POR_MES;
	
--
DROP TABLE CALENDARIO_GLOBAL

CREATE TABLE  CALENDARIO_GLOBAL AS
	WITH calendario_inicio_final_rango AS (
		SELECT
			DATE_ADD(
				LAST_DAY(DATE_SUB(MIN(FECHA_PROCESO), INTERVAL 1 MONTH)),
				INTERVAL 1 DAY
			) AS INICIO_FECHA,
			MAX(FECHA_PROCESO) AS FIN_FECHA
		FROM TEMP_BASE_INICIAL
	),

	TEMP_DIAS_HABILES AS (
		SELECT
			cal.FEC_CALENDARIO AS FECHA_PROCESO,
			cal.IND_DIA_HABIL
		FROM BDS_CALENDARIOS cal
		INNER JOIN calendario_inicio_final_rango r
			ON cal.FEC_CALENDARIO BETWEEN r.INICIO_FECHA AND r.FIN_FECHA
		WHERE cal.COD_CALENDARIO=1
	),
	TEMP_DIAS_HABILES_FINAL AS (
		SELECT
			t1.FECHA_PROCESO,
			t1.IND_DIA_HABIL,
			MAX(t2.FEC_CALENDARIO) AS FECHA_ORIGEN
		FROM TEMP_DIAS_HABILES t1
		INNER JOIN BDS_CALENDARIOS t2
			ON t2.FEC_CALENDARIO <= t1.FECHA_PROCESO
			AND t2.IND_DIA_HABIL = 'S'
		GROUP BY t1.FECHA_PROCESO, t1.IND_DIA_HABIL
	)

	SELECT *  FROM TEMP_DIAS_HABILES_FINAL WHERE FECHA_PROCESO >=@v_fecha_inicio;
	
select MIN(FECHA_PROCESO), MAX(FECHA_PROCESO),COUNT(*) from CALENDARIO_GLOBAL where IND_DIA_HABIL='N'
select * from CALENDARIO_GLOBAL where IND_DIA_HABIL='N'
--

DROP TABLE BASE_TABLA_RANGO_FECHA
	CREATE TABLE BASE_TABLA_RANGO_FECHA AS
	WITH BASE_TABLA_RANGO_FECHA AS (

	SELECT 
		CONCAT(
				o.COD_EMPRESA,'|', 
				o.COD_MODULO,'|', 
				o.COD_SUCURSAL,'|',
				o.COD_MONEDA,'|', 
				o.COD_PAPEL,'|', 
				o.NUM_CUENTA_BT,'|',
				o.COD_OPERACION,'|', 
				o.COD_SUB_OPERACION,'|', 
				o.COD_TIPO_OPERACION
			) AS ID_OPERACION_CIERRE,
		tf.FECHA_PROCESO AS FECHA_PROCESO,
		o.COD_EMPRESA,
		o.COD_SUCURSAL,
		o.COD_RUBRO,
		o.COD_MONEDA,
		o.COD_PAPEL,
		o.NUM_CUENTA_BT,
		o.COD_OPERACION,
		o.COD_EJECUTIVO,
		o.COD_SUB_OPERACION,
		o.COD_TIPO_OPERACION,
		o.COD_MODULO,
		o.COD_MODULO_PRODUCTO, -- NUEVO CAMPO
		o.FEC_VENCIMIENTO,
		o.FEC_VALOR,
		o.IND_CATEGORIA_RIESGO,
		o.COD_ACTI_BCO_CENTRAL,
		o.COD_PRODUCTO,
		o.MTO_SALDO_ORIGEN,
		o.MTO_SALDO_MN,
		o.MTO_SALDO_ME,
		o.MTO_SALDO_MO,
		o.MTO_INTERES,
		o.MTO_PREVISIONES,
		tf.IND_DIA_HABIL,
		CASE
			WHEN tf.FECHA_PROCESO = tf.FECHA_ORIGEN
			THEN 'ORIGINAL'
			ELSE 'COPIA_HABIL'
		END AS TIPO_ORIGEN,
		o.FUENTE,
		o.FECHA_CARGA,
		o.BATCH_ID 
		FROM CALENDARIO_GLOBAL tf
		JOIN TEMP_BASE_COMPLETA_POR_MES o
			ON o.FECHA_PROCESO = tf.FECHA_ORIGEN)
			
	SELECT * FROM BASE_TABLA_RANGO_FECHA;
	
	
	

---------------------------------------p
--
DROP TABLE TABLA_REGISTROS_MISMO_DIA_OPERACIONES
	CREATE TABLE TABLA_REGISTROS_MISMO_DIA_OPERACIONES AS 
		WITH 
		TABLA_REGISTROS_MISMO_DIA_OPERACIONES AS (
			SELECT
				bho.*
			FROM BASE_TABLA_RANGO_FECHA bho WHERE ID_OPERACION_CIERRE  IN(
				SELECT  ID_OPERACION FROM BDS_OPERACIONES)
		)
	SELECT * FROM TABLA_REGISTROS_MISMO_DIA_OPERACIONES;


--

DROP TABLE TABLA_REGISTROS_OPERACIONES_ANTERIORES
	CREATE TABLE TABLA_REGISTROS_OPERACIONES_ANTERIORES AS 
		WITH 
		TABLA_REGISTROS_OPERACIONES_ANTERIORES AS  (

			SELECT
				bho.*
			FROM BASE_TABLA_RANGO_FECHA bho WHERE ID_OPERACION_CIERRE NOT IN(
				SELECT  ID_OPERACION FROM BDS_OPERACIONES
				)

		)
		SELECT * FROM TABLA_REGISTROS_OPERACIONES_ANTERIORES;
		
--
DROP TABLE UNION_ALL_TABLE
	CREATE TABLE UNION_ALL_TABLE AS
	SELECT * FROM TABLA_REGISTROS_MISMO_DIA_OPERACIONES
	UNION ALL 
	SELECT * FROM TABLA_REGISTROS_OPERACIONES_ANTERIORES;

select min(FECHA_PROCESO), MAX(FECHA_PROCESO ) from UNION_ALL_TABLE

DROP TABLE UNION_ALL_TABLE_1


CREATE TABLE UNION_ALL_TABLE_1 AS
	SELECT *
	FROM (
		SELECT
			T.*,
			ROW_NUMBER() OVER (
				PARTITION BY
					ID_OPERACION_CIERRE,
					FECHA_PROCESO,
					COD_EMPRESA,
					COD_SUCURSAL,
					COD_RUBRO,
					COD_MONEDA,
					COD_PAPEL,
					NUM_CUENTA_BT,
					COD_OPERACION,
					COD_SUB_OPERACION,
					COD_TIPO_OPERACION,
					COD_MODULO,
					COD_MODULO_PRODUCTO,
					FEC_VENCIMIENTO,
					FEC_VALOR,
					IND_CATEGORIA_RIESGO,
					COD_ACTI_BCO_CENTRAL,
					COD_PRODUCTO,
					MTO_SALDO_ORIGEN,
					MTO_SALDO_MN,
					MTO_SALDO_ME,
					MTO_SALDO_MO,
					MTO_INTERES,
					MTO_PREVISIONES
				ORDER BY FECHA_CARGA DESC
			) RN
		FROM UNION_ALL_TABLE T
	) X
	WHERE RN = 1;
--- AQUIE TE QUEDASTE
SELECT  MIN(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM UNION_ALL_TABLE_1
SELECT  COUNT(*) FROM UNION_ALL_TABLE_1 -- 36948701


-------------------------------------------------------------------------------------------------------------

SELECT
    D.ID_OPERACION_CIERRE,
    D.FECHA_PROCESO AS FECHA_DOMINGO,
    DATE_SUB(D.FECHA_PROCESO, INTERVAL 1 DAY) AS FECHA_SABADO,
    D.MTO_SALDO_MN AS SALDO_DOMINGO,
    S.MTO_SALDO_MN AS SALDO_SABADO
FROM UNION_ALL_TABLE_1 D
INNER JOIN UNION_ALL_TABLE_1 S
    ON S.ID_OPERACION_CIERRE = D.ID_OPERACION_CIERRE
   AND S.COD_RUBRO = D.COD_RUBRO
   AND S.FECHA_PROCESO = DATE_SUB(D.FECHA_PROCESO,INTERVAL 1 DAY)
WHERE DAYOFWEEK(D.FECHA_PROCESO) = 1   -- Domingo
AND COALESCE(D.MTO_SALDO_MN,0)
    <> COALESCE(S.MTO_SALDO_MN,0); -- DEBE DE SALIR VACIO

SELECT ID_OPERACION_CIERRE,COD_RUBRO, COUNT(*)  FROM UNION_ALL_TABLE_1 GROUP BY ID_OPERACION_CIERRE, COD_RUBRO

SELECT ID_OPERACION_CIERRE, COUNT(*) FROM 	UNION_ALL_TABLE_1  -- 1|405|1|1|0|1471150|467435|0|0
WHERE FECHA_PROCESO >='2026-05-01' AND FECHA_PROCESO <='2026-05-31'
GROUP BY ID_OPERACION_CIERRE
ORDER BY COUNT(*) ASC

DROP TABLE DATAHUB_NULL_FIN_MES

CREATE TABLE DATAHUB_NULL_FIN_MES AS
	SELECT
		ID_OPERACION_CIERRE,
		COD_RUBRO,
		YEAR(FECHA_PROCESO) ANIO,
		MONTH(FECHA_PROCESO) MES,
		MAX(FECHA_PROCESO) ULTIMA_FECHA_REGISTRADA,
		LAST_DAY(MAX(FECHA_PROCESO)) FIN_DE_MES
	FROM UNION_ALL_TABLE_1
	GROUP BY
		ID_OPERACION_CIERRE,
		YEAR(FECHA_PROCESO),
		MONTH(FECHA_PROCESO),
		COD_RUBRO
	HAVING MAX(FECHA_PROCESO) <> LAST_DAY(MAX(FECHA_PROCESO));

select * from DATAHUB_NULL_FIN_MES where ID_OPERACION_CIERRE ='1|405|1|1|0|1448363|2340409|0|0'

DROP TABLE TEMP_AUXILIAR_FIN_MES
select * from DATAHUB_NULL_FIN_MES
SELECT MIN(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM TEMP_AUXILIAR_FIN_MES -- 8766389


CREATE TABLE TEMP_AUXILIAR_FIN_MES AS
	WITH RECURSIVE FECHAS_FALTANTES AS (
		SELECT
			nfm.ID_OPERACION_CIERRE,
			nfm.COD_RUBRO,
			nfm.ANIO,
			nfm.MES,
			DATE_ADD(nfm.ULTIMA_FECHA_REGISTRADA, INTERVAL 1 DAY) AS FECHA_PROCESO,
			nfm.ULTIMA_FECHA_REGISTRADA,
			nfm.FIN_DE_MES
		FROM DATAHUB_NULL_FIN_MES nfm 

		UNION ALL

		SELECT
			ff.ID_OPERACION_CIERRE,
			ff.COD_RUBRO,
			ff.ANIO,
			ff.MES,
			DATE_ADD(ff.FECHA_PROCESO, INTERVAL 1 DAY),
			ff.ULTIMA_FECHA_REGISTRADA,
			ff.FIN_DE_MES
		FROM FECHAS_FALTANTES ff
		WHERE ff.FECHA_PROCESO < ff.FIN_DE_MES--  AND  
	)
	SELECT -- FROM FECHAS_FALTANTES ff WHERE ID_OPERACION_CIERRE='1|405|1|1|0|1448363|2340409|0|0'
		urt.ID_OPERACION_CIERRE,
		ff.FECHA_PROCESO,
		urt.COD_EMPRESA,
		urt.COD_SUCURSAL,
		urt.COD_RUBRO,
		urt.COD_MONEDA,
		urt.COD_PAPEL,
		urt.NUM_CUENTA_BT,
		urt.COD_OPERACION,
		urt.COD_EJECUTIVO,
		urt.COD_SUB_OPERACION,
		urt.COD_TIPO_OPERACION,
		urt.COD_MODULO,
		urt.COD_MODULO_PRODUCTO,
		urt.FEC_VENCIMIENTO,
		urt.FEC_VALOR,
		urt.IND_CATEGORIA_RIESGO,
		urt.COD_ACTI_BCO_CENTRAL,
		urt.COD_PRODUCTO,
		0 AS TOTAL_MTO_SALDO_ORIGEN,
		0 AS TOTAL_SALDO_MN,
		0 AS TOTAL_SALDO_ME,
		0 AS TOTAL_SALDO_MO,
		0 AS TOTAL_MTO_INTERES,
		0 AS TOTAL_MTO_PREVISIONES,
		'S' AS IND_DIA_HABIL,
		urt.FUENTE,
		urt.FECHA_CARGA,
		urt.BATCH_ID
	FROM FECHAS_FALTANTES ff
	INNER JOIN UNION_ALL_TABLE_1 urt
		ON urt.ID_OPERACION_CIERRE = ff.ID_OPERACION_CIERRE
	AND urt.FECHA_PROCESO = ff.ULTIMA_FECHA_REGISTRADA
	AND urt.COD_RUBRO = ff.COD_RUBRO
	-- AND urt.TIPO_ORIGEN <> 'COPIA_HABIL'
	WHERE ff.FECHA_PROCESO < @v_fecha_fin;
		
	SELECT * FROM TEMP_AUXILIAR_FIN_MES WHERE ID_OPERACION_CIERRE='1|405|1|1|0|1448363|2340409|0|0'
		
		
SELECT * FROM 
TEMP_AUXILIAR_FIN_MES WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1471150|467435|0|0'

SELECT * FROM UNION_ALL_TABLE_1
 WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1471150|467435|0|0'
--

DROP TABLE DATAHUB_NULL_INTERMEDIO
select * from DATAHUB_NULL_INTERMEDIO

CREATE TABLE DATAHUB_NULL_INTERMEDIO AS
		WITH RECURSIVE CALENDARIO AS (

			SELECT
				ID_OPERACION_CIERRE,
				COD_RUBRO,
				YEAR(MIN(FECHA_PROCESO)) ANIO,
				MONTH(MIN(FECHA_PROCESO)) MES,
				MIN(FECHA_PROCESO) FECHA_PROCESO,
				MAX(FECHA_PROCESO) FECHA_FIN
			FROM UNION_ALL_TABLE_1
			GROUP BY
				ID_OPERACION_CIERRE,
				COD_RUBRO,
				YEAR(FECHA_PROCESO),
				MONTH(FECHA_PROCESO)

			UNION ALL

			SELECT
				ID_OPERACION_CIERRE,
				COD_RUBRO,
				ANIO,
				MES,
				DATE_ADD(FECHA_PROCESO, INTERVAL 1 DAY),
				FECHA_FIN
			FROM CALENDARIO
			WHERE FECHA_PROCESO < FECHA_FIN
		)

		SELECT
			C.ID_OPERACION_CIERRE,
			C.COD_RUBRO,
			C.ANIO,
			C.MES,
			C.FECHA_PROCESO
		FROM CALENDARIO C
		LEFT JOIN UNION_ALL_TABLE_1 T
			ON T.ID_OPERACION_CIERRE = C.ID_OPERACION_CIERRE
		AND T.COD_RUBRO = C.COD_RUBRO
		AND T.FECHA_PROCESO = C.FECHA_PROCESO
		WHERE T.ID_OPERACION_CIERRE IS NULL;
--

DROP TABLE TEMP_AUXILIAR_INTERMEDIO


SELECT min(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM TEMP_AUXILIAR_INTERMEDIO  -- 23180638

		CREATE TABLE TEMP_AUXILIAR_INTERMEDIO AS

		SELECT
			A.ID_OPERACION_CIERRE,
			A.FECHA_PROCESO,

			B.COD_EMPRESA,
			B.COD_SUCURSAL,
			B.COD_RUBRO,
			B.COD_MONEDA,
			B.COD_PAPEL,
			B.NUM_CUENTA_BT,
			B.COD_OPERACION,
			B.COD_EJECUTIVO,
			B.COD_SUB_OPERACION,
			B.COD_TIPO_OPERACION,
			B.COD_MODULO,
			B.COD_MODULO_PRODUCTO,
			B.FEC_VENCIMIENTO,
			B.FEC_VALOR,
			B.IND_CATEGORIA_RIESGO,
			B.COD_ACTI_BCO_CENTRAL,
			B.COD_PRODUCTO,

			0 AS MTO_SALDO_ORIGEN,
			0 AS MTO_SALDO_MN,
			0 AS MTO_SALDO_ME,
			0 AS MTO_SALDO_MO,
			0 AS MTO_INTERES,
			0 AS MTO_PREVISIONES,

			'S' AS IND_DIA_HABIL,

			B.FUENTE,
			B.FECHA_CARGA,
			B.BATCH_ID

		FROM DATAHUB_NULL_INTERMEDIO A

		JOIN UNION_ALL_TABLE_1 B
		ON B.ID_OPERACION_CIERRE = A.ID_OPERACION_CIERRE
		AND B.COD_RUBRO = A.COD_RUBRO
		AND B.FECHA_PROCESO = (

				SELECT MAX(C.FECHA_PROCESO)
				FROM UNION_ALL_TABLE_1 C
				WHERE C.ID_OPERACION_CIERRE = A.ID_OPERACION_CIERRE
				AND C.COD_RUBRO = A.COD_RUBRO
				AND C.FECHA_PROCESO < A.FECHA_PROCESO
				AND C.TIPO_ORIGEN = 'ORIGINAL'

		);

		
SELECT * FROM 
TEMP_AUXILIAR_INTERMEDIO WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1471150|467435|0|0'

SELECT * FROM UNION_ALL_TABLE_1
 WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1471150|467435|0|0'
		--
		
		DROP TABLE DATAHUB_NULL_INICIO_MES
-- == Completar registros desde el primer dia del mes con registris hasta el primer dia de registro
	CREATE TABLE DATAHUB_NULL_INICIO_MES AS
		SELECT
			ID_OPERACION_CIERRE,
			COD_RUBRO,
			YEAR(FECHA_PROCESO) AS ANIO,
			MONTH(FECHA_PROCESO) AS MES,
			MIN(FECHA_PROCESO) AS PRIMERA_FECHA_REGISTRADA,
			DATE_FORMAT(MIN(FECHA_PROCESO),'%Y-%m-01') AS INICIO_MES
		FROM UNION_ALL_TABLE_1
		GROUP BY
			ID_OPERACION_CIERRE,
			YEAR(FECHA_PROCESO),
			MONTH(FECHA_PROCESO),
			COD_RUBRO
		HAVING MIN(FECHA_PROCESO) <>
			DATE_FORMAT(MIN(FECHA_PROCESO),'%Y-%m-01');
	select * from DATAHUB_NULL_INICIO_MES
--


SELECT  min(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM TEMP_AUXILIAR_INICIO_MES  -- 71426421
DROP TABLE TEMP_AUXILIAR_INICIO_MES

	CREATE TABLE TEMP_AUXILIAR_INICIO_MES AS
	WITH RECURSIVE FECHAS_FALTANTES AS (

		SELECT
			ID_OPERACION_CIERRE,
			COD_RUBRO,
			ANIO,
			MES,
			INICIO_MES AS FECHA_PROCESO,
			PRIMERA_FECHA_REGISTRADA
		FROM DATAHUB_NULL_INICIO_MES

		UNION ALL

		SELECT
			ID_OPERACION_CIERRE,
			COD_RUBRO,
			ANIO,
			MES,
			DATE_ADD(FECHA_PROCESO,INTERVAL 1 DAY),
			PRIMERA_FECHA_REGISTRADA
		FROM FECHAS_FALTANTES
		WHERE DATE_ADD(FECHA_PROCESO,INTERVAL 1 DAY)
			< PRIMERA_FECHA_REGISTRADA
	)
	SELECT
		x.ID_OPERACION_CIERRE,
		ff.FECHA_PROCESO,
		x.COD_EMPRESA,
		x.COD_SUCURSAL,
		x.COD_RUBRO,
		x.COD_MONEDA,
		x.COD_PAPEL,
		x.NUM_CUENTA_BT,
		x.COD_OPERACION,
		x.COD_EJECUTIVO,
		x.COD_SUB_OPERACION,
		x.COD_TIPO_OPERACION,
		x.COD_MODULO,
		x.COD_MODULO_PRODUCTO,
		x.FEC_VENCIMIENTO,
		x.FEC_VALOR,
		x.IND_CATEGORIA_RIESGO,
		x.COD_ACTI_BCO_CENTRAL,
		x.COD_PRODUCTO,
		0 AS MTO_SALDO_ORIGEN,
		0 AS MTO_SALDO_MN,
		0 AS MTO_SALDO_ME,
		0 AS MTO_SALDO_MO,
		0 AS MTO_INTERES,
		0 AS MTO_PREVISIONES,
		'S' AS IND_DIA_HABIL,
		x.FUENTE,
		x.FECHA_CARGA,
		x.BATCH_ID
	FROM FECHAS_FALTANTES ff
	INNER JOIN UNION_ALL_TABLE_1 x
		ON x.ID_OPERACION_CIERRE = ff.ID_OPERACION_CIERRE
		AND x.COD_RUBRO = ff.COD_RUBRO
	AND x.FECHA_PROCESO = ff.PRIMERA_FECHA_REGISTRADA
	AND x.TIPO_ORIGEN <> 'COPIA_HABIL'
		
-- -----------------------------------------------------------------EJECUTANDO
SELECT * FROM 
TEMP_AUXILIAR_INICIO_MES WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1471150|467435|0|0'

SELECT * FROM UNION_ALL_TABLE_1
 WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1471150|467435|0|0'

SELECT count(*) FROM UNION_ALL_TABLE_1  -- 35 337 879


SELECT MIN(FECHA_PROCESO) , MAX(FECHA_PROCESO) FROM TEMP_AUXILIAR_INICIO_MES WHERE ID_OPERACION_CIERRE ='1|404|1|1|0|1411955|382135|0|0'-- 57964185
SELECT COUNT(*) FROM UNION_ALL_TABLE_1 WHERE ID_OPERACION_CIERRE ='1|404|1|1|0|1411955|382135|0|0'-- 57964185
SELECT  @v_fecha_inicio
	INSERT INTO  UNION_ALL_TABLE_1(ID_OPERACION_CIERRE,
		FECHA_PROCESO,
		COD_EMPRESA,
		COD_SUCURSAL,
		COD_RUBRO,
		COD_MONEDA,
		COD_PAPEL,
		NUM_CUENTA_BT,
		COD_OPERACION,
		COD_EJECUTIVO,
		COD_SUB_OPERACION,
		COD_TIPO_OPERACION,
		COD_MODULO,
		COD_MODULO_PRODUCTO,
		FEC_VENCIMIENTO,
		FEC_VALOR,
		IND_CATEGORIA_RIESGO,
		COD_ACTI_BCO_CENTRAL,
		COD_PRODUCTO,
		MTO_SALDO_ORIGEN,
		MTO_SALDO_MN,
		MTO_SALDO_ME,
		MTO_SALDO_MO,
		MTO_INTERES,
		MTO_PREVISIONES,
		IND_DIA_HABIL,
		FUENTE,
		FECHA_CARGA,
		BATCH_ID )
		SELECT t.*
		FROM TEMP_AUXILIAR_INICIO_MES t
		WHERE NOT EXISTS (
			SELECT 1
			FROM UNION_ALL_TABLE_1 u
			WHERE u.ID_OPERACION_CIERRE = t.ID_OPERACION_CIERRE
			AND u.COD_RUBRO = t.COD_RUBRO
			AND u.FECHA_PROCESO = t.FECHA_PROCESO
		)
		AND  t.FECHA_PROCESO >= @v_fecha_inicio;
	



SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*) FROM UNION_ALL_TABLE_1 
WHERE FECHA_PROCESO >='2026-05-01'  AND FECHA_PROCESO <= '2026-05-31' GROUP BY  ID_OPERACION_CIERRE ,COD_RUBRO

	SELECT COUNT(*) FROM UNION_ALL_TABLE_1 -- 68 045 490
	INSERT INTO  UNION_ALL_TABLE_1(
		ID_OPERACION_CIERRE,
		FECHA_PROCESO,
		COD_EMPRESA,
		COD_SUCURSAL,
		COD_RUBRO,
		COD_MONEDA,
		COD_PAPEL,
		NUM_CUENTA_BT,
		COD_OPERACION,
		COD_EJECUTIVO,
		COD_SUB_OPERACION,
		COD_TIPO_OPERACION,
		COD_MODULO,
		COD_MODULO_PRODUCTO,
		FEC_VENCIMIENTO,
		FEC_VALOR,
		IND_CATEGORIA_RIESGO,
		COD_ACTI_BCO_CENTRAL,
		COD_PRODUCTO,
		MTO_SALDO_ORIGEN,
		MTO_SALDO_MN,
		MTO_SALDO_ME,
		MTO_SALDO_MO,
		MTO_INTERES,
		MTO_PREVISIONES,
		IND_DIA_HABIL,
		FUENTE,
		FECHA_CARGA,
		BATCH_ID )
		SELECT t.*
		FROM TEMP_AUXILIAR_INTERMEDIO t
		WHERE NOT EXISTS (
			SELECT 1
			FROM UNION_ALL_TABLE_1 u
			WHERE u.ID_OPERACION_CIERRE = t.ID_OPERACION_CIERRE
			AND u.COD_RUBRO = t.COD_RUBRO
			AND u.FECHA_PROCESO = t.FECHA_PROCESO
		)
		AND t.FECHA_PROCESO >= @v_fecha_inicio;
		SELECT COUNT(*) FROM UNION_ALL_TABLE_1  -- 68 373 221
--
SELECT * FROM TEMP_AUXILIAR_INTERMEDIO WHERE ID_OPERACION_CIERRE='1|465|1|2|0|1099708|11632|0|0'


	INSERT INTO  UNION_ALL_TABLE_1(
		ID_OPERACION_CIERRE,
		FECHA_PROCESO,
		COD_EMPRESA,
		COD_SUCURSAL,
		COD_RUBRO,
		COD_MONEDA,
		COD_PAPEL,
		NUM_CUENTA_BT,
		COD_OPERACION,
		COD_EJECUTIVO,
		COD_SUB_OPERACION,
		COD_TIPO_OPERACION,
		COD_MODULO,
		COD_MODULO_PRODUCTO,
		FEC_VENCIMIENTO,
		FEC_VALOR,
		IND_CATEGORIA_RIESGO,
		COD_ACTI_BCO_CENTRAL,
		COD_PRODUCTO,
		MTO_SALDO_ORIGEN,
		MTO_SALDO_MN,
		MTO_SALDO_ME,
		MTO_SALDO_MO,
		MTO_INTERES,
		MTO_PREVISIONES,
		IND_DIA_HABIL,
		FUENTE,
		FECHA_CARGA,
		BATCH_ID )
		SELECT t.*
		FROM TEMP_AUXILIAR_FIN_MES t
		WHERE NOT EXISTS (
			SELECT 1
			FROM UNION_ALL_TABLE_1 u
			WHERE u.ID_OPERACION_CIERRE = t.ID_OPERACION_CIERRE
			AND u.COD_RUBRO = t.COD_RUBRO
			AND u.FECHA_PROCESO = t.FECHA_PROCESO
		)		
		AND t.FECHA_PROCESO >= @v_fecha_inicio;
	
--


SELECT * FROM TEMP_AUXILIAR_FIN_MES
 WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1448363|2340409|0|0'
 
 SELECT count(*) FROM UNION_ALL_TABLE_1  -- 57656809
 WHERE ID_OPERACION_CIERRE ='1|405|1|1|0|1448363|2340409|0|0'
 
 
SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*) FROM UNION_ALL_TABLE_1 
WHERE FECHA_PROCESO >='2026-04-01'  AND FECHA_PROCESO <= '2026-04-30' -- and ID_OPERACION_CIERRE='1|465|1|2|0|1099708|11632|0|0'
GROUP BY  ID_OPERACION_CIERRE ,COD_RUBRO
ORDER BY COUNT(*) ASC
	-- FEBRERO COMPLETO
SELECT * FROM UNION_ALL_TABLE_1 WHERE ID_OPERACION_CIERRE='1|33|1|1|0|1334942|221519|0|0' AND COD_RUBRO='5424010302210141'
	
	SELECT *FROM UNION_ALL_TABLE_1  -- 68813746
	
SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO, COUNT(*) FROM 	UNION_ALL_TABLE_1
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
ORDER BY COUNT(*) DESC
	
	UPDATE UNION_ALL_TABLE_1 U
		INNER JOIN CALENDARIO_GLOBAL T
		ON T.FECHA_PROCESO = U.FECHA_PROCESO
		SET U.IND_DIA_HABIL = T.IND_DIA_HABIL;

	
	
	-- VAIDACION DE DOMINGOS 
	
	SELECT
    D.ID_OPERACION_CIERRE,
    D.FECHA_PROCESO AS FECHA_DOMINGO,
    DATE_SUB(D.FECHA_PROCESO, INTERVAL 1 DAY) AS FECHA_SABADO,
    D.MTO_SALDO_MN AS SALDO_DOMINGO,
    S.MTO_SALDO_MN AS SALDO_SABADO
FROM UNION_ALL_TABLE_1 D
INNER JOIN UNION_ALL_TABLE_1 S
    ON S.ID_OPERACION_CIERRE = D.ID_OPERACION_CIERRE
   AND S.COD_RUBRO = D.COD_RUBRO
   AND S.FECHA_PROCESO = DATE_SUB(D.FECHA_PROCESO,INTERVAL 1 DAY)
WHERE DAYOFWEEK(D.FECHA_PROCESO) = 1   -- Domingo
AND COALESCE(D.MTO_SALDO_MN,0)
    <> COALESCE(S.MTO_SALDO_MN,0);
	
	
--
SELECT * FROM UNION_ALL_TABLE_1 WHERE FECHA_PROCESO  IN('2026-01-08', '2026-03-07') AND ID_OPERACION_CIERRE ='1|404|1|1|0|1128719|30358|14|0'

SELECT COUNT(*) DIFERENCIAS
FROM UNION_ALL_TABLE_1 D
INNER JOIN UNION_ALL_TABLE_1 S
    ON S.ID_OPERACION_CIERRE = D.ID_OPERACION_CIERRE
   AND S.COD_RUBRO = D.COD_RUBRO
   AND S.FECHA_PROCESO = DATE_SUB(D.FECHA_PROCESO,INTERVAL 1 DAY)
WHERE DAYOFWEEK(D.FECHA_PROCESO) = 1
AND COALESCE(D.MTO_SALDO_MN,0)
    <> COALESCE(S.MTO_SALDO_MN,0);
	--
	
	DROP TABLE TABLA_FINAL_SIN_NOMBRE
	

	CREATE TABLE TABLA_FINAL_SIN_NOMBRE AS 
	WITH BASE_14_1_VIGENTE_MO AS (
		SELECT ID_OPERACION_CIERRE,COD_RUBRO, FECHA_PROCESO,MTO_SALDO_MO AS MTO_SALDO_VIGENTE_MO, MTO_SALDO_MN AS MTO_SALDO_VIGENTE_MN FROM UNION_ALL_TABLE_1
			WHERE SUBSTR(COD_RUBRO,1,4) LIKE '14_1' GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
	),
	BASE_14_3_MTO_RESTRUCTURADO_MO AS (
		SELECT  ID_OPERACION_CIERRE,COD_RUBRO,FECHA_PROCESO,MTO_SALDO_MO AS MTO_SALDO_RESTRUCTURADO_MO,  MTO_SALDO_MN AS MTO_SALDO_RESTRUCTURADO_MN  FROM UNION_ALL_TABLE_1 pc 
		WHERE SUBSTR(COD_RUBRO,1,4) LIKE '14_3' GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO,COD_RUBRO ),
	MTO_14_4_SALDO_REFINANCIADO_MO AS (
		SELECT    ID_OPERACION_CIERRE,COD_RUBRO, FECHA_PROCESO,MTO_SALDO_MO AS MTO_SALDO_REFINANCIADO_MO , MTO_SALDO_MN AS MTO_SALDO_REFINANCIADO_MN  FROM UNION_ALL_TABLE_1 pc 
		WHERE SUBSTR(COD_RUBRO,1,4) LIKE '14_4' GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO,COD_RUBRO
	),
	BASE_14_5_MTO_VENCIDO_MO AS (
		SELECT   ID_OPERACION_CIERRE,COD_RUBRO,FECHA_PROCESO,MTO_SALDO_MO AS MTO_SALDO_VENCIDO_MO, MTO_SALDO_MN AS MTO_SALDO_VENCIDO_MN  FROM UNION_ALL_TABLE_1 pc 
		WHERE SUBSTR(COD_RUBRO,1,4) LIKE '14_5'GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO,COD_RUBRO ),
	BASE_14_6_MTO_JUDICIA_MO AS (
		SELECT    ID_OPERACION_CIERRE,COD_RUBRO,FECHA_PROCESO,MTO_SALDO_MO AS MTO_SALDO_JUDIAL_MO, MTO_SALDO_MN AS MTO_SALDO_JUDICIAL_MN  FROM UNION_ALL_TABLE_1 pc 
		WHERE SUBSTR(COD_RUBRO,1,4) LIKE '14_6' GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO,COD_RUBRO
	),
	BASE_TABLA AS (
		SELECT DISTINCT 
			bt.ID_OPERACION_CIERRE,
			bt.FECHA_PROCESO,
			bt.COD_EMPRESA,
			bt.COD_SUCURSAL,
			bt.COD_RUBRO,
			bt.COD_MONEDA,
			bt.COD_PAPEL,
			bt.NUM_CUENTA_BT,
			bt.COD_OPERACION,
			bt.COD_EJECUTIVO,
			bt.COD_SUB_OPERACION,
			bt.COD_TIPO_OPERACION,
			bt.COD_MODULO,
			bt.FEC_VENCIMIENTO,
			bt.FEC_VALOR,
			bt.IND_CATEGORIA_RIESGO,
			bt.COD_ACTI_BCO_CENTRAL,
			bt.COD_PRODUCTO,
			bt.MTO_SALDO_ORIGEN,
			bt.MTO_SALDO_MN,
			bt.MTO_SALDO_ME,
			bt.MTO_SALDO_MO,
			bt.MTO_INTERES,
			bt.MTO_PREVISIONES,
			bt.FUENTE,
			bt.IND_DIA_HABIL,
			bt.FECHA_CARGA,
			bt.BATCH_ID
		FROM UNION_ALL_TABLE_1 bt WHERE LEFT(bt.COD_RUBRO, 4) IN (
		'1401','1403','1404','1405','1406',
		'1411','1413','1414','1415','1416',
		'1421','1423','1424','1425','1426'
	))
	SELECT 
		bt.ID_OPERACION_CIERRE,
		bt.FECHA_PROCESO,
		bt.COD_EMPRESA,
		bt.COD_SUCURSAL,
		bt.COD_RUBRO,
		bt.COD_MONEDA,
		bt.COD_PAPEL,
		bt.NUM_CUENTA_BT,
		bt.COD_OPERACION,
		bt.COD_EJECUTIVO,
		bt.COD_SUB_OPERACION,
		bt.COD_TIPO_OPERACION,
		bt.COD_MODULO,
		bt.FEC_VENCIMIENTO,
		bt.FEC_VALOR,
		bt.IND_CATEGORIA_RIESGO,
		bt.COD_ACTI_BCO_CENTRAL,
		bt.COD_PRODUCTO,
		bt.MTO_SALDO_ORIGEN,
		bt.MTO_SALDO_MN,
		bt.MTO_SALDO_ME,
		bt.MTO_SALDO_MO,
		bt.MTO_INTERES,
		bt.MTO_PREVISIONES,
		COALESCE(bv.MTO_SALDO_VIGENTE_MO, 0) MTO_SALDO_VIGENTE_MO,
		COALESCE(bres.MTO_SALDO_RESTRUCTURADO_MO,0) MTO_SALDO_RESTRUCTURADO_MO,
		COALESCE(bref.MTO_SALDO_REFINANCIADO_MO ,0) MTO_SALDO_REFINANCIADO_MO,
		COALESCE(bven.MTO_SALDO_VENCIDO_MO,0) MTO_SALDO_VENCIDO_MO,
		COALESCE(bjud.MTO_SALDO_JUDIAL_MO,0) MTO_SALDO_JUDIAL_MO,
		-- 
		COALESCE(bv.MTO_SALDO_VIGENTE_MN, 0) MTO_SALDO_VIGENTE_MN,
		COALESCE(bres.MTO_SALDO_RESTRUCTURADO_MN,0) MTO_SALDO_RESTRUCTURADO_MN,
		COALESCE(bref.MTO_SALDO_REFINANCIADO_MN ,0) MTO_SALDO_REFINANCIADO_MN,
		COALESCE(bven.MTO_SALDO_VENCIDO_MN,0) MTO_SALDO_VENCIDO_MN,
		COALESCE(bjud.MTO_SALDO_JUDICIAL_MN,0) MTO_SALDO_JUDICIAL_MN,
		bt.FUENTE,
		bt.IND_DIA_HABIL,
		bt.FECHA_CARGA,
		bt.BATCH_ID
	FROM  BASE_TABLA bt
	LEFT JOIN BASE_14_1_VIGENTE_MO bv ON bt.ID_OPERACION_CIERRE = bv.ID_OPERACION_CIERRE   and bt.FECHA_PROCESO = bv.FECHA_PROCESO and bt.COD_RUBRO = bv.COD_RUBRO
	LEFT JOIN BASE_14_3_MTO_RESTRUCTURADO_MO bres ON bt.ID_OPERACION_CIERRE = bres.ID_OPERACION_CIERRE  and bt.FECHA_PROCESO = bres.FECHA_PROCESO and bt.COD_RUBRO = bres.COD_RUBRO
	LEFT JOIN MTO_14_4_SALDO_REFINANCIADO_MO bref ON bt.ID_OPERACION_CIERRE = bref.ID_OPERACION_CIERRE  and bt.FECHA_PROCESO = bref.FECHA_PROCESO and bt.COD_RUBRO = bref.COD_RUBRO
	LEFT JOIN BASE_14_5_MTO_VENCIDO_MO bven ON bt.ID_OPERACION_CIERRE = bven.ID_OPERACION_CIERRE and bt.FECHA_PROCESO = bven.FECHA_PROCESO and bt.COD_RUBRO = bven.COD_RUBRO
	LEFT JOIN BASE_14_6_MTO_JUDICIA_MO bjud ON bt.ID_OPERACION_CIERRE = bjud.ID_OPERACION_CIERRE and bt.FECHA_PROCESO = bjud.FECHA_PROCESO and bt.COD_RUBRO = bjud.COD_RUBRO;

---------------------
-- Nueva logica DE INSGRESOS , COMISION, GASTOS DE PROVISION


-- .............................
select * from TABLA_FINAL_SIN_NOMBRE
			
SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*)FROM TABLA_FINAL_SIN_NOMBRE 
WHERE FECHA_PROCESO >='2026-04-01'  AND FECHA_PROCESO <= '2026-04-30' GROUP BY  ID_OPERACION_CIERRE ,COD_RUBRO
ORDER BY COUNT(*) ASC
			


SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO, COUNT(*) FROM 	TABLA_FINAL_SIN_NOMBRE
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
ORDER BY COUNT(*) DESC
--


DROP TABLE SIN_DUPLICADO

CREATE TABLE SIN_DUPLICADO AS
SELECT  * FROM TABLA_FINAL_SIN_NOMBRE
GROUP BY ID_OPERACION_CIERRE, COD_RUBRO, FECHA_PROCESO;	
	
--
SELECT  MIN(FECHA_PROCESO),MAX(FECHA_PROCESO) FROM SIN_DUPLICADO

select * from TABLA_FINAL_SIN_NOMBRE_PASIVOS

UPDATE UNION_ALL_TABLE_1 U
		INNER JOIN CALENDARIO_GLOBAL T
		ON T.FECHA_PROCESO = U.FECHA_PROCESO
		SET U.IND_DIA_HABIL = T.IND_DIA_HABIL;



DROP TABLE TABLA_FINAL_SIN_NOMBRE_PASIVOS
	CREATE TABLE TABLA_FINAL_SIN_NOMBRE_PASIVOS AS 
	SELECT * FROM UNION_ALL_TABLE_1
	WHERE COD_MODULO IN (20,120,321,22,185,184,162,155,21) OR 
	(COD_MODULO = 183 AND LEFT(COD_RUBRO, 4) IN('1201','1211','1221'
	)) OR
	(LEFT(COD_RUBRO, 2) IN('56','57','46','49','68','41'
	))OR
	(LEFT(COD_RUBRO, 4) IN('5121','5111','5112','5111','5114','5124','5117','5127','4111',
	'4121','4112','4122','4113','4123','4117','4127','4116','4126','4115','4125','4312','4322',
	'5211','5221','5214','5224','5212','5222','4211','4221','411907','412907','4212','4222',
	'5118','5128','4118','4128','4511','4521','4512','4522','4513','4523','4514','4524','4411','4421',
	'4413','4423','5213','5223','4313','4323','5415','5425','5416','5426',
	'5114','5124','5117','5127'
	))OR 
	(LEFT(COD_RUBRO,6) IN ('512302','511302','511304','512304','512305','511305'
	,'511504','512504','511901','512901','411925','412925','412401','411401','411901','412901','411908','412908','411909','412909',
	'411922','412922','411923','412923','511925','512925','411925','412925','521204','522204','521205','522205',
	'511916','512916','411916','412916','511918','512918','411918','412918','511919','512919',
	'411919','412919','411920','412920','511926','512926','411926','412926','511903','512903','411903','412903',
	'511928','512928','511507','512507','511910','512910','411910','412910','431401','432401',
	'431402','432402'
	))OR
	(LEFT(COD_RUBRO,6) IN ('411402','412402','411403','412403','411408','412408'
	,'411404','412404','411405','412405','411406','412406','411407','412407','511927','512927','431501','432501',
	'431502','432502','431506','432506','521204','522204','521205','522205','421204','422204',
	'421205','422205','411905','412905','421204','422204','421205','422205','411911','412911',
	'411912','412912','511301','512301','511911','512911','511912','512912',
	'511306','512306','511915','512915','411915','412915','411913','412913','511303','512303',
	'511913','512913','411914','412914','511914','512914','511917','512917','411917','412917',
	'511904','512904','411904','412904','431504','432504','431503','432503','431508','432508',
	'431509','432509'
	))OR
	(LEFT(COD_RUBRO,8) IN ('51191703','51291703','51192403','51292403','41191703','41291703','41192403','41292403',
	'51191703','51291703','51292403','51192403','41191703','41291703','41192403','41292403',
	'51191703','51291703','41191703','41291703','43150501','43250501','43150505','43250505',
	'43150506','43250506','54140103','54240103'
	))OR
	(LEFT(COD_RUBRO,10) IN ('5119170102','5129170102','5119170202','5129170202','5119240101','5129240101',
	'4119170102','4129170102','4119170202','4129170202','4119240101','4129240101',
	'5119170102','5129170102','5119170202','5129170202','5119240101','5129240101','4119170102','4129170102',
	'4119170202','4129170202','4119240101','4129240101','4315050401','4325050401','4315050402','4325050402',
	'5119170102','5129170102','5119170202','5129170202','5119240102','5129240102','4119170102','4129170102'
	)) OR
	(LEFT(COD_RUBRO,10) IN ('4119170202','4129170202','4119240102','4129240102','5119170102','5129170102','5119170202',
	'5129170202','5119240101','5129240101'
	))OR COD_RUBRO LIKE ('4312030106030101%')
	OR COD_RUBRO LIKE ('4312030106030501%')
	OR COD_RUBRO LIKE('4312030201060101%')
	OR COD_RUBRO LIKE('4312030201060501%')
	OR COD_RUBRO LIKE ('4312030701000103%')
	OR COD_RUBRO LIKE ('4312030702000103%');
	

select * from TABLA_FINAL_SIN_NOMBRE_PASIVOS WHERE COD_MODULO =183
	
	--
	SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*)FROM TABLA_FINAL_SIN_NOMBRE_PASIVOS 
WHERE FECHA_PROCESO >='2026-04-01'  AND FECHA_PROCESO <= '2026-04-30' GROUP BY  ID_OPERACION_CIERRE ,COD_RUBRO
ORDER BY COUNT(*) desc
			

SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO, COUNT(*) FROM 	TABLA_FINAL_SIN_NOMBRE_PASIVOS
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
ORDER BY COUNT(*) desc
	
	--
	
	DROP TABLE SIN_DUPLICADO_PASIVOS
	CREATE TABLE SIN_DUPLICADO_PASIVOS AS
	SELECT  * FROM TABLA_FINAL_SIN_NOMBRE_PASIVOS
	GROUP BY ID_OPERACION_CIERRE, COD_RUBRO, FECHA_PROCESO;
	
DROP TABLE UNION_PASIVOS_ACTIVOS;
	
	
	CREATE TABLE UNION_PASIVOS_ACTIVOS
	AS 
	SELECT ID_OPERACION_CIERRE
		,FECHA_PROCESO
		,COD_EMPRESA
		,COD_SUCURSAL
		,COD_RUBRO
		,COD_MONEDA
		,COD_PAPEL
		,NUM_CUENTA_BT
		,COD_OPERACION
		,COD_EJECUTIVO
		,COD_SUB_OPERACION
		,COD_TIPO_OPERACION
		,COD_MODULO
		,FEC_VENCIMIENTO
		,FEC_VALOR
		,IND_CATEGORIA_RIESGO
		,COD_ACTI_BCO_CENTRAL
		,COD_PRODUCTO
		,MTO_SALDO_ORIGEN
		,MTO_SALDO_MN
		,MTO_SALDO_ME
		,MTO_SALDO_MO
		,MTO_INTERES
		,MTO_PREVISIONES
		,0 MTO_SALDO_VIGENTE_MO
		,0 MTO_SALDO_RESTRUCTURADO_MO
		,0 MTO_SALDO_REFINANCIADO_MO
		,0 MTO_SALDO_VENCIDO_MO
		,0 MTO_SALDO_JUDIAL_MO
		,0 MTO_SALDO_VIGENTE_MN
		,0 MTO_SALDO_RESTRUCTURADO_MN
		,0 MTO_SALDO_REFINANCIADO_MN
		,0 MTO_SALDO_VENCIDO_MN
		,0 MTO_SALDO_JUDIAL_MN
		,FUENTE
		,IND_DIA_HABIL
		,FECHA_CARGA
		,BATCH_ID 
	FROM SIN_DUPLICADO_PASIVOS
	UNION ALL
	SELECT * FROM SIN_DUPLICADO;
		
----

	SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*)FROM UNION_PASIVOS_ACTIVOS 
WHERE FECHA_PROCESO >='2026-05-01'  AND FECHA_PROCESO <= '2026-05-31' GROUP BY  ID_OPERACION_CIERRE ,COD_RUBRO
ORDER BY COUNT(*) ASC
			
SELECT ID_OPERACION_CIERRE, COD_RUBRO,FECHA_PROCESO,COUNT(*)FROM UNION_PASIVOS_ACTIVOS WHERE ID_OPERACION_CIERRE='1|239|1|1|0|1477143|454645|0|0'
GROUP BY ID_OPERACION_CIERRE, COD_RUBRO,FECHA_PROCESO


SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO, COUNT(*) FROM 	UNION_PASIVOS_ACTIVOS
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
ORDER BY COUNT(*) DESC



SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*) FROM 	UNION_PASIVOS_ACTIVOS
GROUP BY ID_OPERACION_CIERRE, COD_RUBRO
ORDER BY COUNT(*) DESC
-- ELIMINACION DE DUPLICADOS:

drop table UNION_PASIVOS_ACTIVOS_SIN_DUPLICADO

SELECT * FROM UNION_PASIVOS_ACTIVOS_SIN_DUPLICADO
CREATE TABLE UNION_PASIVOS_ACTIVOS_SIN_DUPLICADO AS
WITH BASE AS
(
    SELECT *,
           ROW_NUMBER() OVER
           (
                PARTITION BY
                    ID_OPERACION_CIERRE,
                    FECHA_PROCESO,
                    COD_RUBRO
                ORDER BY FECHA_PROCESO DESC
           ) RN
    FROM UNION_PASIVOS_ACTIVOS
)
SELECT *
FROM BASE
WHERE RN = 1;

drop table UNION_PASIVOS_ACTIVOS_DEPURADA         ---------------------------

CREATE TABLE UNION_PASIVOS_ACTIVOS_DEPURADA AS
WITH BASE AS (
    SELECT
        A.*,
        COUNT(*) OVER (
            PARTITION BY
                ID_OPERACION_CIERRE,
                FECHA_PROCESO,
                COD_RUBRO
        ) AS CNT
    FROM UNION_PASIVOS_ACTIVOS_SIN_DUPLICADO A
)
SELECT *
FROM BASE
WHERE
    CNT = 1
    OR
    (
        CNT > 1
        AND (
               COALESCE(MTO_SALDO_ORIGEN,0) <> 0
            OR COALESCE(MTO_SALDO_MN,0) <> 0
            OR COALESCE(MTO_SALDO_ME,0) <> 0
            OR COALESCE(MTO_SALDO_MO,0) <> 0
        )
    );



---
SELECT * FROM UNION_PASIVOS_ACTIVOS_DEPURADA WHERE ID_OPERACION_CIERRE='1|21|40|1|0|1443514|0|3|13'

SELECT ID_OPERACION_CIERRE, COD_RUBRO, COUNT(*)FROM UNION_PASIVOS_ACTIVOS_DEPURADA 
WHERE FECHA_PROCESO >='2026-04-01'  AND FECHA_PROCESO <= '2026-04-30' GROUP BY  ID_OPERACION_CIERRE ,COD_RUBRO
ORDER BY COUNT(*) ASC
			
SELECT * FROM UNION_PASIVOS_ACTIVOS_DEPURADA WHERE ID_OPERACION_CIERRE = '1|140|1|1|0|1461045|222200453|0|73'
SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO, COUNT(*) FROM 	UNION_PASIVOS_ACTIVOS_DEPURADA
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
ORDER BY COUNT(*) DESC


----
SELECT MIN(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM UNION_PASIVOS_ACTIVOS_DEPURADA

--

DROP TABLE UNION_PASIVOS_ACTIVOS_DEPURADA_INT;

CREATE TABLE UNION_PASIVOS_ACTIVOS_DEPURADA_INT
SELECT
    ID_OPERACION_CIERRE
	,FECHA_PROCESO
	,COD_EMPRESA
	,COD_SUCURSAL
	,COD_MONEDA
	,COD_PAPEL
	,NUM_CUENTA_BT
	,COD_OPERACION
	,COD_EJECUTIVO
	,COD_SUB_OPERACION
	,COD_TIPO_OPERACION
	,COD_MODULO
	,FEC_VENCIMIENTO
	,FEC_VALOR
	,IND_CATEGORIA_RIESGO
	,COD_ACTI_BCO_CENTRAL
	,FUENTE
	,IND_DIA_HABIL
	,FECHA_CARGA
	,BATCH_ID,
    CASE
        WHEN SUBSTRING(COD_RUBRO, 3, 1) = '1'
            THEN 1
        WHEN SUBSTRING(COD_RUBRO, 3, 1) = '2'
            THEN 2
        ELSE NULL
    END AS TIPO_MONEDA,

    CASE
        WHEN LEFT(COD_RUBRO, 4) IN ('5124', '5114')
            THEN MTO_SALDO_MN
        ELSE NULL
    END AS MTO_INGRESO_MN_MES,

    CASE
        WHEN LEFT(COD_RUBRO, 4) IN ('5117', '5127')
            THEN MTO_SALDO_MN
        ELSE NULL
    END AS MTO_COMISION_MN_MES,

    CASE
        WHEN LEFT(COD_RUBRO, 2) IN ('41')
            THEN MTO_SALDO_MN
        ELSE NULL
    END AS MTO_GASTO_MN_MES,

    CASE
        WHEN LEFT(COD_RUBRO, 8) IN ('54140103', '54240103')
            THEN MTO_SALDO_MN
        ELSE NULL
    END AS MTO_REVERSO_PROVISION,

    CASE
        WHEN COD_RUBRO LIKE '4312030106030501%'
		OR COD_RUBRO LIKE '4322030106030501%'
          OR COD_RUBRO LIKE '4312030201060101%'
		  OR COD_RUBRO LIKE '4322030201060101%'
          OR COD_RUBRO LIKE '4312030201060501%'
		  OR COD_RUBRO LIKE '4322030201060501%'
          OR COD_RUBRO LIKE '4312030701000103%'
		  OR COD_RUBRO LIKE '4322030701000103%'
          OR COD_RUBRO LIKE '4312030702000103%'
		  OR COD_RUBRO LIKE '4322030702000103%'
            THEN MTO_SALDO_MN
        ELSE NULL
    END AS MTO_PROVISION_MN_MES

FROM UNION_PASIVOS_ACTIVOS_DEPURADA
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO, COD_RUBRO
-------------------DESDE AQUI-----------------------------------
DROP TABLE TEMPORAL_TABLE
CREATE TABLE TEMPORAL_TABLE AS 
SELECT 
ID_OPERACION_CIERRE
,FECHA_PROCESO
,COD_EMPRESA
,COD_SUCURSAL
,COD_MONEDA
,COD_PAPEL
,NUM_CUENTA_BT
,COD_OPERACION
,COD_EJECUTIVO
,COD_SUB_OPERACION
,COD_TIPO_OPERACION
,COD_MODULO
,TIPO_MONEDA
,FEC_VENCIMIENTO
,FEC_VALOR
,IND_CATEGORIA_RIESGO
,COD_ACTI_BCO_CENTRAL
,FUENTE
,IND_DIA_HABIL
,FECHA_CARGA
,BATCH_ID FROM  UNION_PASIVOS_ACTIVOS_DEPURADA_INT
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO

---


SELECT MIN(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM TEMPORAL_TABLE
--


	SELECT ID_OPERACION_CIERRE, COUNT(*)FROM TEMPORAL_TABLE 
WHERE FECHA_PROCESO >='2026-05-01'  AND FECHA_PROCESO <= '2026-05-31' GROUP BY  ID_OPERACION_CIERRE
ORDER BY COUNT(*) ASC
			

SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COUNT(*) FROM 	TEMPORAL_TABLE
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO
ORDER BY COUNT(*) DESC

SELECT COUNT(DISTINCT ID_OPERACION_CIERRE) FROM TEMPORAL_TABLE tt  -- 598778

SELECT ID_OPERACION_CIERRE, COUNT(*) FROM TABLA_2_HAMER_V2 tt 
where  FECHA_PROCESO >='2026-01-01' and  FECHA_PROCESO <= '2026-01-31'
GROUP BY ID_OPERACION_CIERRE  
ORDER BY COUNT(*) desc
--


drop table TABLA_1_HAMER ------------------------ -- AHORA AQUI

CREATE TABLE TABLA_1_HAMER AS
SELECT
    ad.ID_OPERACION_CIERRE,
    ad.FECHA_PROCESO,
    DAY(ad.FECHA_PROCESO) AS NUM_DIA_MES,
    DAY(LAST_DAY(ad.FECHA_PROCESO)) AS TOTAL_DIAS_MES,

    SUM(ad.MTO_SALDO_ORIGEN) AS TOTAL_DIA_SALDO_ORIGEN,
    SUM(ad.MTO_SALDO_MN) AS TOTAL_DIA_SALDO_MN,
    SUM(ad.MTO_SALDO_ME) AS TOTAL_DIA_SALDO_ME,
    SUM(ad.MTO_SALDO_MO) AS TOTAL_DIA_SALDO_MO,

    SUM(ad.MTO_INTERES) AS TOTAL_DIA_INTERES,
    SUM(ad.MTO_PREVISIONES) AS TOTAL_DIA_PREVISIONES,

    SUM(ad.MTO_SALDO_VIGENTE_MO) AS TOTAL_DIA_SALDO_VIGENTE_MO,
    SUM(ad.MTO_SALDO_RESTRUCTURADO_MO) AS TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
    SUM(ad.MTO_SALDO_REFINANCIADO_MO) AS TOTAL_DIA_SALDO_REFINANCIADO_MO,
    SUM(ad.MTO_SALDO_VENCIDO_MO) AS TOTAL_DIA_SALDO_VENCIDO_MO,
    SUM(ad.MTO_SALDO_JUDIAL_MO) AS TOTAL_DIA_SALDO_JUDIAL_MO,

    SUM(ad.MTO_SALDO_VIGENTE_MN) AS TOTAL_DIA_SALDO_VIGENTE_MN,
    SUM(ad.MTO_SALDO_RESTRUCTURADO_MN) AS TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
    SUM(ad.MTO_SALDO_REFINANCIADO_MN) AS TOTAL_DIA_SALDO_REFINANCIADO_MN,
    SUM(ad.MTO_SALDO_VENCIDO_MN) AS TOTAL_DIA_SALDO_VENCIDO_MN,
    SUM(ad.MTO_SALDO_JUDIAL_MN) AS TOTAL_DIA_SALDO_JUDIAL_MN,
	
	SUM(adt.MTO_INGRESO_MN_MES) AS TOTAL_DIA_INGRESO_MN,
	SUM(adt.MTO_COMISION_MN_MES) AS TOTAL_DIA_COMISION_MN,
	SUM(adt.MTO_GASTO_MN_MES) AS TOTAL_DIA_GASTO_MN,
	SUM(adt.MTO_REVERSO_PROVISION) AS TOTAL_DIA_REVERSO_PROVISION_MN
	
FROM UNION_PASIVOS_ACTIVOS_DEPURADA ad
INNER JOIN UNION_PASIVOS_ACTIVOS_DEPURADA_INT adt
ON ad.ID_OPERACION_CIERRE= adt.ID_OPERACION_CIERRE AND ad.FECHA_PROCESO = adt.FECHA_PROCESO
GROUP BY
    ad.ID_OPERACION_CIERRE,
    ad.FECHA_PROCESO;

SELECT COUNT(DISTINCT ID_OPERACION_CIERRE) FROM TABLA_1_HAMER tt  -- 606229

SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COUNT(*) FROM TABLA_1_HAMER tt 
GROUP BY ID_OPERACION_CIERRE , FECHA_PROCESO 
ORDER BY COUNT(*) DESC

DROP TABLE TABLA_2_HAMER_V2

CREATE TABLE TABLA_2_HAMER_V2 AS
SELECT
    ID_OPERACION_CIERRE,
    FECHA_PROCESO,
	LAST_DAY(
		DATE_SUB(FECHA_PROCESO, INTERVAL 1 MONTH)
		) AS FECHA_CORTE_ULTIMO,
    NUM_DIA_MES,
    TOTAL_DIAS_MES,
    TOTAL_DIA_SALDO_ORIGEN,
    TOTAL_DIA_SALDO_MN,
    TOTAL_DIA_SALDO_ME,
    TOTAL_DIA_SALDO_MO,
    TOTAL_DIA_INTERES,
    TOTAL_DIA_PREVISIONES,
    TOTAL_DIA_SALDO_VIGENTE_MO,
    TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
    TOTAL_DIA_SALDO_REFINANCIADO_MO,
    TOTAL_DIA_SALDO_VENCIDO_MO,
    TOTAL_DIA_SALDO_JUDIAL_MO,
    TOTAL_DIA_SALDO_VIGENTE_MN,
    TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
    TOTAL_DIA_SALDO_REFINANCIADO_MN,
    TOTAL_DIA_SALDO_VENCIDO_MN,
    TOTAL_DIA_SALDO_JUDIAL_MN,
	TOTAL_DIA_INGRESO_MN,
	TOTAL_DIA_COMISION_MN,
	TOTAL_DIA_GASTO_MN,
	TOTAL_DIA_REVERSO_PROVISION_MN,
    CAST(
        SUM(TOTAL_DIA_SALDO_ORIGEN) OVER (
            PARTITION BY ID_OPERACION_CIERRE,
                         YEAR(FECHA_PROCESO),
                         MONTH(FECHA_PROCESO)
            ORDER BY FECHA_PROCESO
        ) / NUM_DIA_MES
        AS DECIMAL(18,4)
    ) AS AVG_SALDO_ORIGEN,
    CAST(
        SUM(TOTAL_DIA_SALDO_MN) OVER (
            PARTITION BY ID_OPERACION_CIERRE,
                         YEAR(FECHA_PROCESO),
                         MONTH(FECHA_PROCESO)
            ORDER BY FECHA_PROCESO
        ) / NUM_DIA_MES
        AS DECIMAL(18,4)
    ) AS AVG_SALDO_MN,
    CAST(
        SUM(TOTAL_DIA_SALDO_ME) OVER (
            PARTITION BY ID_OPERACION_CIERRE,
                         YEAR(FECHA_PROCESO),
                         MONTH(FECHA_PROCESO)
            ORDER BY FECHA_PROCESO
        ) / NUM_DIA_MES
        AS DECIMAL(18,4)
    ) AS AVG_SALDO_ME,

    CAST(
        SUM(TOTAL_DIA_SALDO_MO) OVER (
            PARTITION BY ID_OPERACION_CIERRE,
                         YEAR(FECHA_PROCESO),
                         MONTH(FECHA_PROCESO)
            ORDER BY FECHA_PROCESO
        ) / NUM_DIA_MES
        AS DECIMAL(18,4)
    ) AS AVG_SALDO_MO,
    CAST(
	    SUM(TOTAL_DIA_INTERES) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_INTERES,
	
	CAST(
	    SUM(TOTAL_DIA_PREVISIONES) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_PREVISIONES,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_VIGENTE_MO) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_VIGENTE_MO,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_RESTRUCTURADO_MO) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_RESTRUCTURADO_MO,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_REFINANCIADO_MO) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_REFINANCIADO_MO,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_VENCIDO_MO) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_VENCIDO_MO,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_JUDIAL_MO) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_JUDIAL_MO,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_VIGENTE_MN) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_VIGENTE_MN,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_RESTRUCTURADO_MN) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_RESTRUCTURADO_MN,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_REFINANCIADO_MN) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_REFINANCIADO_MN,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_VENCIDO_MN) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_VENCIDO_MN,
	
	CAST(
	    SUM(TOTAL_DIA_SALDO_JUDIAL_MN) OVER (
	        PARTITION BY ID_OPERACION_CIERRE,
	                     YEAR(FECHA_PROCESO),
	                     MONTH(FECHA_PROCESO)
	        ORDER BY FECHA_PROCESO
	    ) / NUM_DIA_MES
	    AS DECIMAL(18,4)
	) AS AVG_SALDO_JUDIAL_MN
FROM TABLA_1_HAMER;



INSERT INTO  BDS_SALDOS_OPERATIVOS_PREVIOS (ID_OPERACION_CIERRE
,FECHA_PROCESO
,FECHA_CORTE_ULTIMO
,COD_EMPRESA
,COD_SUCURSAL
,COD_MONEDA
,COD_PAPEL
,NUM_CUENTA_BT
,COD_OPERACION
,COD_SUB_OPERACION
,COD_TIPO_OPERACION
,COD_MODULO
,TIPO_MONEDA
,COD_EJECUTIVO
,FEC_VENCIMIENTO
,FEC_VALOR
,IND_CATEGORIA_RIESGO
,COD_ACTI_BCO_CENTRAL
,TOTAL_DIAS_MES
,TOTAL_DIA_SALDO_ORIGEN
,TOTAL_DIA_SALDO_MN
,TOTAL_DIA_SALDO_ME
,TOTAL_DIA_SALDO_MO
,TOTAL_DIA_INTERES
,TOTAL_DIA_PREVISIONES
,TOTAL_DIA_SALDO_VIGENTE_MO
,TOTAL_DIA_SALDO_RESTRUCTURADO_MO
,TOTAL_DIA_SALDO_REFINANCIADO_MO
,TOTAL_DIA_SALDO_VENCIDO_MO
,TOTAL_DIA_SALDO_JUDIAL_MO
,TOTAL_DIA_SALDO_VIGENTE_MN
,TOTAL_DIA_SALDO_RESTRUCTURADO_MN
,TOTAL_DIA_SALDO_REFINANCIADO_MN
,TOTAL_DIA_SALDO_VENCIDO_MN
,TOTAL_DIA_SALDO_JUDIAL_MN
,TOTAL_DIA_COMISION_MN
,TOTAL_DIA_INGRESO_MN
,TOTAL_DIA_GASTO_MN
,TOTAL_DIA_REVERSO_PROVISION_MN
,MTO_INGRESO_MN_MES
,MTO_COMISION_MN_MES
,MTO_GASTO_MN_MES
,MTO_PROVISION_MN_MES
,AVG_SALDO_ORIGEN
,AVG_SALDO_MN
,AVG_SALDO_ME
,AVG_SALDO_MO
,AVG_INTERES
,AVG_PROVISIONES
,AVG_SALDO_VIGENTE_MO
,AVG_SALDO_RESTRUCTURADO_MO
,AVG_SALDO_REFINANCIADO_MO
,AVG_SALDO_VENCIDO_MO
,AVG_SALDO_JUDIAL_MO
,AVG_SALDO_VIGENTE_MN
,AVG_SALDO_RESTRUCTURADO_MN
,AVG_SALDO_REFINANCIADO_MN
,AVG_SALDO_VENCIDO_MN
,AVG_SALDO_JUDIAL_MN
,FUENTE
,IND_DIA_HABIL
,FECHA_CARGA
,BATCH_ID)
SELECT 
	A.ID_OPERACION_CIERRE
	,A.FECHA_PROCESO
	,B.FECHA_CORTE_ULTIMO
	,A.COD_EMPRESA
	,A.COD_SUCURSAL
	,A.COD_MONEDA
	,A.COD_PAPEL
	,A.NUM_CUENTA_BT
	,A.COD_OPERACION
	,A.COD_SUB_OPERACION
	,A.COD_TIPO_OPERACION
	,A.COD_MODULO
	,A.TIPO_MONEDA
	,A.COD_EJECUTIVO
	,A.FEC_VENCIMIENTO
	,A.FEC_VALOR
	,A.IND_CATEGORIA_RIESGO
	,A.COD_ACTI_BCO_CENTRAL,
	B.TOTAL_DIAS_MES,
    B.TOTAL_DIA_SALDO_ORIGEN,
    B.TOTAL_DIA_SALDO_MN,
    B.TOTAL_DIA_SALDO_ME,
    B.TOTAL_DIA_SALDO_MO,
    B.TOTAL_DIA_INTERES,
    B.TOTAL_DIA_PREVISIONES,
    B.TOTAL_DIA_SALDO_VIGENTE_MO,
    B.TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
    B.TOTAL_DIA_SALDO_REFINANCIADO_MO,
    B.TOTAL_DIA_SALDO_VENCIDO_MO,
    B.TOTAL_DIA_SALDO_JUDIAL_MO,
    B.TOTAL_DIA_SALDO_VIGENTE_MN,
    B.TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
    B.TOTAL_DIA_SALDO_REFINANCIADO_MN,
    B.TOTAL_DIA_SALDO_VENCIDO_MN,
    B.TOTAL_DIA_SALDO_JUDIAL_MN,
	B.TOTAL_DIA_COMISION_MN,
	B.TOTAL_DIA_INGRESO_MN,
	B.TOTAL_DIA_GASTO_MN,
	B.TOTAL_DIA_REVERSO_PROVISION_MN,
	0 AS MTO_INGRESO_MN_MES,
	0 AS MTO_COMISION_MN_MES,
	0 AS MTO_GASTO_MN_MES,
	0 AS MTO_PROVISION_MN_MES,
    B.AVG_SALDO_ORIGEN,
    B.AVG_SALDO_MN,
    B.AVG_SALDO_ME,
    B.AVG_SALDO_MO,
    B.AVG_INTERES,
    B.AVG_PREVISIONES AS AVG_PROVISIONES,
    B.AVG_SALDO_VIGENTE_MO,
    B.AVG_SALDO_RESTRUCTURADO_MO,
    B.AVG_SALDO_REFINANCIADO_MO,
    B.AVG_SALDO_VENCIDO_MO,
    B.AVG_SALDO_JUDIAL_MO,
    B.AVG_SALDO_VIGENTE_MN,
    B.AVG_SALDO_RESTRUCTURADO_MN,
    B.AVG_SALDO_REFINANCIADO_MN,
    B.AVG_SALDO_VENCIDO_MN,
    B.AVG_SALDO_JUDIAL_MN
    ,A.FUENTE
	,A.IND_DIA_HABIL
	,A.FECHA_CARGA
	,A.BATCH_ID 
FROM TEMPORAL_TABLE A
INNER JOIN TABLA_2_HAMER_V2 B
    ON A.ID_OPERACION_CIERRE = B.ID_OPERACION_CIERRE
	AND A.FECHA_PROCESO = B.FECHA_PROCESO
WHERE A.FECHA_PROCESO >= @v_fecha_inicio_mes AND A.FECHA_PROCESO < @v_fecha_fin



--- UPDATE DESPUES DE INGRESAR LOS DATOS A LA TABLA 



UPDATE BDS_SALDOS_OPERATIVOS_PREVIOS b
LEFT JOIN BDS_SALDOS_OPERATIVOS_PREVIOS u
    ON u.ID_OPERACION_CIERRE = b.ID_OPERACION_CIERRE
   AND u.FECHA_PROCESO = LAST_DAY(
        DATE_SUB(b.FECHA_PROCESO, INTERVAL 1 MONTH)
   )
SET
    b.MTO_INGRESO_MN_MES =
        b.TOTAL_DIA_INGRESO_MN - COALESCE(u.TOTAL_DIA_INGRESO_MN, 0),

    b.MTO_COMISION_MN_MES =
        b.TOTAL_DIA_COMISION_MN - COALESCE(u.TOTAL_DIA_COMISION_MN, 0),

    b.MTO_GASTO_MN_MES =
        b.TOTAL_DIA_GASTO_MN - COALESCE(u.TOTAL_DIA_GASTO_MN, 0),

    b.MTO_PROVISION_MN_MES =
        b.TOTAL_DIA_REVERSO_PROVISION_MN - COALESCE(u.TOTAL_DIA_REVERSO_PROVISION_MN, 0);



	
	
	
	
	
	
	
	
	
	
	
	
	
	
	--------------FIN --------------------------
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	 

SELECT * FROM TABLA_2_HAMER_V2 WHERE ID_OPERACION_CIERRE ='1|111|1|2|0|1022317|461328|0|10'


SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COUNT(*) FROM 	TABLA_2_HAMER_V2
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO
ORDER BY COUNT(*) DESC

SELECT COUNT(DISTINCT ID_OPERACION_CIERRE) FROM TABLA_2_HAMER_V2 tt  -- 606229

SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COUNT(*) FROM TABLA_2_HAMER_V2 tt 
GROUP BY ID_OPERACION_CIERRE , FECHA_PROCESO 
ORDER BY COUNT(*) ASC
-- DROP TABLE TEMP_HAMER_BDS_SALDOS_OPERATIVOS

-- select * from TEMP_HAMER_BDS_SALDOS_OPERATIVOS
SELECT @v_fecha_fin
SELECT COUNT(*) FROM  BDS_SALDOS_OPERATIVOS  where FECHA_PROCESO >=@v_fecha_inicio_mes AND FECHA_PROCESO <@v_fecha_fin -- 17960940
-- delete from BDS_SALDOS_OPERATIVOS where FECHA_PROCESO >=@v_fecha_inicio_mes AND FECHA_PROCESO <@v_fecha_fin

-----------------------------------------------------------------


-----------------------------------------------------------------

SELECT COUNT(*)  FROM TABLA_2_HAMER_V2 where FECHA_PROCESO >=@v_fecha_inicio_mes AND FECHA_PROCESO <@v_fecha_fin  -- 18140084



-- CREATE TABLE BDS_SALDOS_OPERATIVOS_BKP_NO_ELIMINAR AS
-- SELECT * FROM  BDS_SALDOS_OPERATIVOS

INSERT INTO  BDS_SALDOS_OPERATIVOS_PREVIOS (ID_OPERACION_CIERRE
,FECHA_PROCESO
,FECHA_CORTE_ULTIMO
,COD_EMPRESA
,COD_SUCURSAL
,COD_MONEDA
,COD_PAPEL
,NUM_CUENTA_BT
,COD_OPERACION
,COD_SUB_OPERACION
,COD_TIPO_OPERACION
,COD_MODULO
,TIPO_MONEDA
,COD_EJECUTIVO
,FEC_VENCIMIENTO
,FEC_VALOR
,IND_CATEGORIA_RIESGO
,COD_ACTI_BCO_CENTRAL
,TOTAL_DIAS_MES
,TOTAL_DIA_SALDO_ORIGEN
,TOTAL_DIA_SALDO_MN
,TOTAL_DIA_SALDO_ME
,TOTAL_DIA_SALDO_MO
,TOTAL_DIA_INTERES
,TOTAL_DIA_PREVISIONES
,TOTAL_DIA_SALDO_VIGENTE_MO
,TOTAL_DIA_SALDO_RESTRUCTURADO_MO
,TOTAL_DIA_SALDO_REFINANCIADO_MO
,TOTAL_DIA_SALDO_VENCIDO_MO
,TOTAL_DIA_SALDO_JUDIAL_MO
,TOTAL_DIA_SALDO_VIGENTE_MN
,TOTAL_DIA_SALDO_RESTRUCTURADO_MN
,TOTAL_DIA_SALDO_REFINANCIADO_MN
,TOTAL_DIA_SALDO_VENCIDO_MN
,TOTAL_DIA_SALDO_JUDIAL_MN
,TOTAL_DIA_COMISION_MN
,TOTAL_DIA_INGRESO_MN
,TOTAL_DIA_GASTO_MN
,TOTAL_DIA_REVERSO_PROVISION_MN
,MTO_INGRESO_MN_MES
,MTO_COMISION_MN_MES
,MTO_GASTO_MN_MES
,MTO_PROVISION_MN_MES
,AVG_SALDO_ORIGEN
,AVG_SALDO_MN
,AVG_SALDO_ME
,AVG_SALDO_MO
,AVG_INTERES
,AVG_PROVISIONES
,AVG_SALDO_VIGENTE_MO
,AVG_SALDO_RESTRUCTURADO_MO
,AVG_SALDO_REFINANCIADO_MO
,AVG_SALDO_VENCIDO_MO
,AVG_SALDO_JUDIAL_MO
,AVG_SALDO_VIGENTE_MN
,AVG_SALDO_RESTRUCTURADO_MN
,AVG_SALDO_REFINANCIADO_MN
,AVG_SALDO_VENCIDO_MN
,AVG_SALDO_JUDIAL_MN
,FUENTE
,IND_DIA_HABIL
,FECHA_CARGA
,BATCH_ID)
SELECT 
	A.ID_OPERACION_CIERRE
	,A.FECHA_PROCESO
	,B.FECHA_CORTE_ULTIMO
	,A.COD_EMPRESA
	,A.COD_SUCURSAL
	,A.COD_MONEDA
	,A.COD_PAPEL
	,A.NUM_CUENTA_BT
	,A.COD_OPERACION
	,A.COD_SUB_OPERACION
	,A.COD_TIPO_OPERACION
	,A.COD_MODULO
	,A.TIPO_MONEDA
	,A.COD_EJECUTIVO
	,A.FEC_VENCIMIENTO
	,A.FEC_VALOR
	,A.IND_CATEGORIA_RIESGO
	,A.COD_ACTI_BCO_CENTRAL,
	B.TOTAL_DIAS_MES,
    B.TOTAL_DIA_SALDO_ORIGEN,
    B.TOTAL_DIA_SALDO_MN,
    B.TOTAL_DIA_SALDO_ME,
    B.TOTAL_DIA_SALDO_MO,
    B.TOTAL_DIA_INTERES,
    B.TOTAL_DIA_PREVISIONES,
    B.TOTAL_DIA_SALDO_VIGENTE_MO,
    B.TOTAL_DIA_SALDO_RESTRUCTURADO_MO,
    B.TOTAL_DIA_SALDO_REFINANCIADO_MO,
    B.TOTAL_DIA_SALDO_VENCIDO_MO,
    B.TOTAL_DIA_SALDO_JUDIAL_MO,
    B.TOTAL_DIA_SALDO_VIGENTE_MN,
    B.TOTAL_DIA_SALDO_RESTRUCTURADO_MN,
    B.TOTAL_DIA_SALDO_REFINANCIADO_MN,
    B.TOTAL_DIA_SALDO_VENCIDO_MN,
    B.TOTAL_DIA_SALDO_JUDIAL_MN,
	B.TOTAL_DIA_COMISION_MN,
	B.TOTAL_DIA_INGRESO_MN,
	B.TOTAL_DIA_GASTO_MN,
	B.TOTAL_DIA_REVERSO_PROVISION_MN,
	0 AS MTO_INGRESO_MN_MES,
	0 AS MTO_COMISION_MN_MES,
	0 AS MTO_GASTO_MN_MES,
	0 AS MTO_PROVISION_MN_MES,
    B.AVG_SALDO_ORIGEN,
    B.AVG_SALDO_MN,
    B.AVG_SALDO_ME,
    B.AVG_SALDO_MO,
    B.AVG_INTERES,
    B.AVG_PREVISIONES AS AVG_PROVISIONES,
    B.AVG_SALDO_VIGENTE_MO,
    B.AVG_SALDO_RESTRUCTURADO_MO,
    B.AVG_SALDO_REFINANCIADO_MO,
    B.AVG_SALDO_VENCIDO_MO,
    B.AVG_SALDO_JUDIAL_MO,
    B.AVG_SALDO_VIGENTE_MN,
    B.AVG_SALDO_RESTRUCTURADO_MN,
    B.AVG_SALDO_REFINANCIADO_MN,
    B.AVG_SALDO_VENCIDO_MN,
    B.AVG_SALDO_JUDIAL_MN
    ,A.FUENTE
	,A.IND_DIA_HABIL
	,A.FECHA_CARGA
	,A.BATCH_ID 
FROM TEMPORAL_TABLE A
INNER JOIN TABLA_2_HAMER_V2 B
    ON A.ID_OPERACION_CIERRE = B.ID_OPERACION_CIERRE
	AND A.FECHA_PROCESO = B.FECHA_PROCESO
WHERE A.FECHA_PROCESO >= @v_fecha_inicio_mes AND A.FECHA_PROCESO < @v_fecha_fin













SELECT * FROM BDS_SALDOS_OPERATIVOS_H4


UPDATE BDS_SALDOS_OPERATIVOS hb
LEFT JOIN BDS_SALDOS_CIERRE sc
    ON sc.ID_OPERACION = hb.ID_OPERACION_CIERRE
   AND sc.FECHA_PROCESO = hb.FECHA_PROCESO
SET hb.COD_EJECUTIVO = sc.COD_EJECUTIVO;



FINAL DEL SP


SELECT * FROM BDS_SALDOS_OPERATIVOS A WHERE ID_OPERACION_CIERRE='1|239|1|1|0|1461769|465607|0|0'
AND  A.FECHA_PROCESO >= @v_fecha_inicio_mes AND A.FECHA_PROCESO <= @v_fecha_fin ORDER BY FECHA_PROCESO DESC


SELECT ID_OPERACION_CIERRE, FECHA_PROCESO, COUNT(*) FROM 	TEMPORAL_TABLE
GROUP BY ID_OPERACION_CIERRE, FECHA_PROCESO
ORDER BY COUNT(*) DESC

SELECT COUNT(DISTINCT ID_OPERACION_CIERRE) FROM TEMPORAL_TABLE  -- 590320

SELECT COUNT(DISTINCT ID_OPERACION_CIERRE) FROM TABLA_2_HAMER_V2
-- TESTEO DE BOQUES
SELECT ID_OPERACION_CIERRE, COUNT(*) FROM 	BDS_SALDOS_OPERATIVOS_HB
WHERE FECHA_PROCESO >='2026-05-01' AND FECHA_PROCESO <='2026-05-31'
GROUP BY ID_OPERACION_CIERRE
ORDER BY COUNT(*) ASC

----
-- DELETE FROM BDS_SALDOS_OPERATIVOS_HB WHERE FECHA_PROCESO >='2026-02-01' and FECHA_PROCESO <=@v_fecha_fin


SELECT * FROM BDS_SALDOS_OPERATIVOS_HB WHERE TOTAL_DIA_SALDO_VIGENTE_MO IS NOT  NULL

 WITH BASE AS (
    SELECT
        ID_OPERACION_CIERRE,
        MAX(FECHA_PROCESO) AS FECHA_PROCESO,
        SUM(TOTAL_SALDO_MN) /
        DAY(LAST_DAY(MAX(FECHA_PROCESO))) AS TOTAL_AVG_SALDO_MN
    FROM BDS_SALDOS_OPERATIVOS_HB
    GROUP BY
        YEAR(FECHA_PROCESO),
        MONTH(FECHA_PROCESO),
        ID_OPERACION_CIERRE
),
BASE_2 AS (
    SELECT
        ID_OPERACION_CIERRE,
        FECHA_PROCESO,
        TOTAL_AVG_SALDO_MN
    FROM BDS_SALDOS_OPERATIVOS_HB
    WHERE FECHA_PROCESO IN (
        '2026-01-31',
        '2026-02-28',
        '2026-03-31',
        '2026-04-30',
        '2026-05-31',
        '2026-06-30'
    )
)
SELECT
    A.ID_OPERACION_CIERRE,
    A.FECHA_PROCESO,
    A.TOTAL_AVG_SALDO_MN AS TOTAL_AVG_BASE,
    B.TOTAL_AVG_SALDO_MN AS TOTAL_AVG_BASE_2,
    ABS(ROUND(A.TOTAL_AVG_SALDO_MN,3)  - ROUND( B.TOTAL_AVG_SALDO_MN,3)) AS DIFERENCIA
FROM BASE A
INNER JOIN BASE_2 B
    ON A.ID_OPERACION_CIERRE = B.ID_OPERACION_CIERRE
   AND A.FECHA_PROCESO = B.FECHA_PROCESO
WHERE IFNULL(A.TOTAL_AVG_SALDO_MN,0)
    <> IFNULL(B.TOTAL_AVG_SALDO_MN,0)
ORDER BY
	ABS(ROUND(A.TOTAL_AVG_SALDO_MN,3)  - ROUND( B.TOTAL_AVG_SALDO_MN,3))
    DESC
    

SELECT MIN(FECHA_PROCESO), MAX(FECHA_PROCESO) FROM TEMP_HAMER_BDS_SALDOS_OPERATIVOS


select * from BDS_SALDOS_OPERATIVOS_HB where ID_OPERACION_CIERRE='1|239|1|1|0|1370581|431489|0|0' AND MONTH(FECHA_PROCESO)=3