CREATE TABLE  ODS_PATRIMONIO_EFECTIVO  (
   FECHA_PROCESO  date DEFAULT NULL,
   COD_EMPRESA  decimal(3,0) DEFAULT NULL,
   NUM_CODIGO  decimal(5,0) DEFAULT NULL,
   PERIODO  varchar(16)   DEFAULT NULL,
   MTO_PATRIMONIO_EFECTIVO  varchar(40)   DEFAULT NULL,
   FUENTE  varchar(250)   DEFAULT NULL,
   FECHA_CARGA  datetime DEFAULT NULL,
   BATCH_ID  varchar(25)   DEFAULT NULL,
  , SHARD KEY () 
)