CREATE TABLE  ODS_CALENDARIOS  (
   FECHA_PROCESO     date           DEFAULT NULL,
   COD_CALENDARIO    int(11)        DEFAULT NULL,
   FEC_CALENDARIO    date           DEFAULT NULL,
   IND_DIA_HABIL     varchar(1)       DEFAULT NULL,
   FUENTE            varchar(250)     DEFAULT 'BANTOTAL',
   FECHA_CARGA       datetime       DEFAULT CURRENT_TIMESTAMP,
   BATCH_ID          varchar(25)      DEFAULT NULL,
  CONSTRAINT  UK_ODS_CALENDARIOS_01  UNIQUE ( COD_CALENDARIO , FEC_CALENDARIO ),
  SHARD KEY   ( COD_CALENDARIO , FEC_CALENDARIO ),
)