CREATE TABLE  ODS_CELULAR  (
   FECHA_PROCESO        date NOT NULL,
   COD_EMPRESA          int(11) NOT NULL,
   NUM_CUENTA_BT        int(11) NOT NULL,
   COD_DOMICILIO        int(11) NOT NULL,
   NUM_CORRELATIVO      int(11) NOT NULL,
   NUM_TELEFONO         varchar(20)   DEFAULT NULL,
   FUENTE               varchar(250)   DEFAULT 'BANTOTAL',
   FECHA_CARGA          datetime DEFAULT CURRENT_TIMESTAMP,
   BATCH_ID             varchar(25)   DEFAULT NULL,
  SHARD KEY  ( COD_EMPRESA , NUM_CUENTA_BT , COD_DOMICILIO , NUM_CORRELATIVO ),
  CONSTRAINT PK_ODS_CELULAR  UNIQUE ( COD_EMPRESA , NUM_CUENTA_BT , COD_DOMICILIO , NUM_CORRELATIVO )
) 