CREATE TABLE CU_REPORTE_POSICION_ME
(
FECHA_PROCESO       DATE,
NIVEL_01            VARCHAR(250),
NIVEL_02            VARCHAR(250),
COD_RUBRO_SBS       VARCHAR(100),
COD_RUBRO_BT        VARCHAR(100),
DES_RUBRO           VARCHAR (250),
COD_MONEDA_SALDO    VARCHAR(10),
COD_MONEDA_RUBRO    VARCHAR(1),
SALDO_MO            DECIMAL(15,2),
SALDO_ME            DECIMAL(15,2),
SALDO_MN            DECIMAL(15,2),
VAR_SALDO_MES_MO    DECIMAL(15,2),
VAR_SALDO_MES_ME    DECIMAL(15,2),
VAR_SALDO_MES_MN    DECIMAL(15,2)
);