CREATE TABLE CU_REPORTE_DETALLE_PRODUCTOS
(
    FECHA_PROCESO       DATE,
    NIVEL_01            VARCHAR(200),
    NIVEL_02            VARCHAR(200),
    NIVEL_03            VARCHAR(200),
    COD_RUBRO_SBS       VARCHAR(25),
    COD_RUBRO_BT        VARCHAR(100),
    DES_RUBRO           VARCHAR (250),
    COD_MONEDA_SALDO    VARCHAR(10),
    COD_MONEDA_RUBRO    VARCHAR(1),
    DES_MONEDA          VARCHAR(200),
    MTO_SALDO_MO            DECIMAL(15,2),
    MTO_SALDO_ME            DECIMAL(15,2),
    MTO_SALDO_MN            DECIMAL(15,2),
    MTO_SALDO_MES_MO    DECIMAL(15,2),
    MTO_SALDO_MES_ME    DECIMAL(15,2),
    MTO_SALDO_MES_MN    DECIMAL(15,2)
);