CREATE TABLE  BDS_RUBRO  (
	FEC_PROCESO                DATE 		NOT NULL     COMMENT 'Fecha de proceso o vigencia del registro',
	COD_RUBRO                  VARCHAR(20)  NOT NULL     COMMENT 'Código único identificador del rubro',
	COD_TITULO                 INT 			DEFAULT NULL COMMENT 'Código de título contable o agrupador principal',
	COD_CAPITULO               INT 			DEFAULT NULL COMMENT 'Código de capítulo dentro de la estructura del rubro',
	COD_PLAZO                  INT 			DEFAULT NULL COMMENT 'Código de clasificación por plazo',
	COD_GRUPO                  INT 			DEFAULT NULL COMMENT 'Código de grupo funcional del rubro',
	COD_SUB_RUBRO              INT 			DEFAULT NULL COMMENT 'Código de sub-rubro asociado',
	COD_SUB_SUB_RUBRO          INT 			DEFAULT NULL COMMENT 'Código de sub-sub-rubro asociado',
	DES_RUBRO                  VARCHAR(40)	DEFAULT NULL  COMMENT 'Descripción funcional del rubro',
	IND_TRATAM_ESPEC           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de tratamiento especial del rubro',
	IND_SIGNO_POSIT            VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que define si el saldo se maneja con signo positivo',
	IND_ANALIZ_PLAZO_BCU       VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de análisis por plazo requerido para reportes regulatorios',
	IND_ANALIZ_RESID           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de análisis por residencia del cliente',
	IND_FECHA_VALOR            VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que requiere fecha valor en operaciones',
	IND_FECHA_VENCIM           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que requiere fecha de vencimiento',
	IND_PERM_SOBREG            VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que permite sobregiros',
	IND_VO_BO_SOBREG           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que requiere aprobación para sobregiros',
	IND_BAJA_PARCIAL           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que permite bajas parciales',
	IND_INCREMENTO             VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que permite incrementos de saldo o monto',
	IND_FORZ_ALTA_INVERT       VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de alta forzada para inversiones',
	COD_MOVIMIENTO             VARCHAR(1) 	DEFAULT NULL COMMENT 'Código de tipo de movimiento asociado al rubro',
	IND_CAJA                   VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de aplicación para operaciones de caja',
	IND_RESIDENTE              VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de control por condición de residencia',
	COD_MODULO                 VARCHAR(1) 	DEFAULT NULL COMMENT 'Código de módulo funcional de Bantotal',
	IND_CUENTA                 VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de uso en cuentas',
	IND_OPERACION              VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de uso en operaciones',
	IND_SUBOPERACION           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de uso en suboperaciones',
	IND_TEXTO_HIST             VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que requiere texto histórico o glosa',
	IND_MONED_ORIG             VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que requiere moneda origen',
	IND_MONED_EXTR             VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que permite moneda extranjera',
	COD_ACTIV_BCU              VARCHAR(1) 	DEFAULT NULL COMMENT 'Código de actividad regulatoria o contable',
	IND_DETALLE_OPERAC         VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que requiere detalle de operación',
	NUM_NIVEL_CONSULTA         INT     	   	DEFAULT NULL COMMENT 'Nivel de consulta o jerarquía del rubro',
	IND_PROMEDIO_SALDO         VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de cálculo de promedio de saldo',
	IND_PROM_SALDO_SOBREG      VARCHAR(1)  	DEFAULT NULL COMMENT 'Indicador de promedio de saldo para sobregiros',
	IND_DEVENGA                VARCHAR(1)  	DEFAULT NULL COMMENT 'Indicador de devengamiento',
	IND_DEVENG_TIPO_DESCUEN    VARCHAR(1)  	DEFAULT NULL COMMENT 'Indicador de devengamiento sujeto a tipo de descuento',
	IND_DEVENGA_AMORT          VARCHAR(1)  	DEFAULT NULL COMMENT 'Indicador de devengamiento por amortización',
	IND_DEVENGA_CUENTA_CORR    VARCHAR(1)  	DEFAULT NULL COMMENT 'Indicador de devengamiento para cuentas corrientes',
	IND_DEVENGA_CAJA_AHORRO    VARCHAR(1)  	DEFAULT NULL COMMENT 'Indicador de devengamiento para cajas de ahorro',
	COD_RUBRO_PERSONAL         VARCHAR(1)  	DEFAULT NULL COMMENT 'Código o indicador de rubro personalizado',
	COD_TIPO_OPERAC            INT  		DEFAULT NULL COMMENT 'Código de tipo de operación asociada',
	IND_INCL_CONVERS_CASA_MATR VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de inclusión en conversión de casa matriz',
	IND_EXCL_CONVERS_CASA_MATR VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de exclusión en conversión de casa matriz',
	COD_RUBRO_EQUIV_CASA_MATR  INT 			DEFAULT NULL COMMENT 'Código de rubro equivalente utilizado por casa matriz',
	IND_ESTRUC_OPERAC          VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de estructura de operación',
	IND_EXTENS_DIRECTA         VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de extensión directa del rubro',
	NUM_FUNC_RUBRO             INT 			DEFAULT NULL COMMENT 'Número o identificador de función asociada al rubro',
	IND_ALTERA_FUNC            VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador que permite alterar la función asociada',
	IND_IMPUTABLE              VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de imputación contable',
	IND_IMPLEMENTADO           VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de implementación en el sistema',
	IND_TRATA_ESPECIES         VARCHAR(1) 	DEFAULT NULL COMMENT 'Indicador de tratamiento de especies o valores',
	TIP_TRATAM_SUBOPERAC       VARCHAR(1) 	DEFAULT NULL COMMENT 'Tipo de tratamiento de suboperación',
	FUENTE                     VARCHAR(250) DEFAULT NULL COMMENT 'Sistema o fuente origen del dato',
	FEC_CARGA                  DATETIME 	DEFAULT NULL COMMENT 'Fecha y hora de carga del registro',
	BATCH_ID                   VARCHAR(25) 	DEFAULT NULL COMMENT 'Identificador único del lote de carga'
	SHARD KEY ( COD_RUBRO ),
	CONSTRAINT  UK_ODS_RUBRO_01  UNIQUE ( COD_RUBRO )
);
