CREATE TABLE BDS_OPERACIONES (
   ID_OPERACION varchar(200) NOT NULL COMMENT 'Identificador único de la operación financiera dentro del sistema origen. Permite individualizar y rastrear cada operación registrada.',
   ID_SALDO_CONTABLE varchar(200) NOT NULL COMMENT 'Identificador único del saldo contable asociado a la operación. Relaciona la operación con su correspondiente registro contable.',
   FECHA_PROCESO date NOT NULL COMMENT 'Fecha de proceso o fecha de negocio en la cual se generó la información de la operación para efectos de cálculo, contabilización o carga.',
   COD_EMPRESA int(11) NOT NULL COMMENT 'Código de la empresa o entidad legal propietaria de la operación financiera.',
   COD_MODULO int(11) NOT NULL COMMENT 'Código del módulo de negocio del sistema origen al que pertenece la operación (créditos, depósitos, inversiones, etc.).',
   COD_SUCURSAL int(11) NOT NULL COMMENT 'Código de la sucursal o agencia donde se originó o administra la operación.',
   COD_MONEDA int(11) NOT NULL COMMENT 'Código de la moneda en la que está expresada la operación y sus saldos monetarios.',
   COD_PAPEL int(11) NOT NULL COMMENT 'Código que identifica el tipo de producto, instrumento financiero o papel asociado a la operación.',
   NUM_CUENTA_BT varchar(15) NOT NULL COMMENT 'Número de cuenta en Bantotal asociado a la operación financiera.',
   COD_EJECUTIVO int(11) DEFAULT NULL COMMENT 'Código del ejecutivo comercial o funcionario responsable de la gestión de la operación.',
   COD_OPERACION varchar(15) NOT NULL COMMENT 'Código principal que identifica la operación dentro del negocio o producto financiero.',
   COD_SUB_OPERACION varchar(11) NOT NULL COMMENT 'Código que identifica una suboperación, componente o desglose específico de la operación principal.',
   COD_TIPO_OPERACION int(11) NOT NULL COMMENT 'Código del tipo de operación financiera según la clasificación definida por el negocio.',
   FEC_ALTA date DEFAULT NULL COMMENT 'Fecha de creación, desembolso, apertura o alta de la operación en el sistema origen.',
   FEC_VENCIMIENTO date DEFAULT NULL COMMENT 'Fecha programada de vencimiento o cancelación de la operación financiera.',
   NUM_DIAS_PLAZO varchar(11) DEFAULT NULL COMMENT 'Cantidad total de días correspondientes al plazo pactado de la operación.',
   TIP_TASA int(11) DEFAULT NULL COMMENT 'Código que identifica la modalidad de tasa aplicada a la operación (fija, variable, mixta, entre otras).',
   PCT_TASA decimal(10,6) DEFAULT NULL COMMENT 'Porcentaje de la tasa de interés ordinaria aplicada a la operación financiera.',
   PCT_TASA_MORA decimal(10,6) DEFAULT NULL COMMENT 'Porcentaje de la tasa de interés moratorio aplicada en caso de incumplimiento o atraso.',
   TIP_DIAS int(11) DEFAULT NULL COMMENT 'Código que identifica la base de cálculo de días utilizada para el cómputo de intereses.',
   TIP_AJUSTE_VENCIMIENTO varchar(1) DEFAULT NULL COMMENT 'Indicador que define la regla de ajuste de la fecha de vencimiento cuando coincide con días no hábiles.',
   TIP_ANIO int(11) DEFAULT NULL COMMENT 'Código que determina la convención de año utilizada para el cálculo financiero (360, 365 u otras).',
   TIP_CALCULO_INTERES varchar(1) DEFAULT NULL COMMENT 'Indicador del método o modalidad utilizada para el cálculo de intereses de la operación.',
   NUM_DIAS_REVISION_TASA varchar(11) DEFAULT NULL COMMENT 'Cantidad de días establecidos para la revisión o actualización periódica de la tasa de interés.',
   MTO_DESEMBOLSADO decimal(17,2) DEFAULT NULL COMMENT 'Monto total desembolsado o entregado al cliente al momento de originar la operación.',
   MTO_INTERES_VEN decimal(17,2) DEFAULT NULL COMMENT 'Monto de intereses vencidos, devengados o pendientes de pago asociados a la operación.',
   FEC_ULTIMA_REV_TASA date DEFAULT NULL COMMENT 'Fecha de la última revisión, actualización o modificación de la tasa de interés aplicada.',
   IND_AFECTADA_IVA varchar(1) DEFAULT NULL COMMENT 'Indicador que señala si la operación está afecta al Impuesto General a las Ventas (IVA/IGV) sobre intereses o comisiones.',
   COD_ESTADO int(11) DEFAULT NULL COMMENT 'Código que representa el estado actual de la operación (vigente, vencida, cancelada, castigada, entre otros).',
   IND_AVISO int(11) DEFAULT NULL COMMENT 'Indicador relacionado con la generación o emisión de avisos, alertas o notificaciones asociadas a la operación.',
   PCT_TASA_PLUS decimal(10,6) DEFAULT NULL COMMENT 'Porcentaje adicional de tasa aplicado sobre la tasa base de la operación como spread, margen o incremento.',
   COD_NUMERO_EVENTOS int(11) DEFAULT NULL COMMENT 'Cantidad o código asociado al número de eventos registrados para la operación durante su ciclo de vida.',
   FEC_BAJA date DEFAULT NULL COMMENT 'Fecha en la que la operación fue dada de baja, cancelada o retirada de vigencia.',
   DES_PERIODO int(11) DEFAULT NULL COMMENT 'Periodicidad o período definido para la operación, utilizado en cálculos financieros o generación de cuotas.',
   TIP_CUENTA int(2) DEFAULT NULL COMMENT 'Código que identifica la clasificación o tipo de cuenta asociada a la operación.',
   FUENTE varchar(250) DEFAULT 'BANTOTAL' COMMENT 'Sistema o fuente de origen desde donde se obtuvo la información de la operación.',
   FECHA_CARGA datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora en que el registro fue cargado o insertado en la plataforma de datos.',
   BATCH_ID varchar(25) DEFAULT NULL COMMENT 'Identificador del proceso batch, lote o ejecución de carga que generó el registro.',
   SHARD KEY (ID_OPERACION, TIP_CUENTA),
   CONSTRAINT UK_ODS_OPERACIONES_01 UNIQUE (ID_OPERACION, ID_SALDO_CONTABLE, TIP_CUENTA)
)
COMMENT='Tabla que almacena el detalle de las operaciones financieras provenientes de Bantotal, incluyendo información contractual, tasas, plazos, montos, estados y atributos necesarios para su seguimiento operativo y contable.';