CREATE TABLE BDS_SALDOS_DIARIOS_CONSOLIDADOS(
   FECHA_PROCESO 		DATE 			NOT NULL 		COMMENT 'Fecha de proceso o cierre contable de los saldos consolidados',
   COD_EMPRESA 		VARCHAR(50) 	DEFAULT NULL 	COMMENT 'Código de la empresa propietaria de la información',
   COD_SUCURSAL 	INT(11) 		NOT NULL 		COMMENT 'Código de la sucursal o agencia',
   COD_RUBRO 		BIGINT(20) 		NOT NULL 		COMMENT 'Código del rubro contable',
   COD_MONEDA 		INT(11) 		NOT NULL 		COMMENT 'Código de la moneda del saldo',
   COD_PAPEL 		INT(11) 		NOT NULL 		COMMENT 'Código del tipo de papel o naturaleza contable',
   COD_MODULO 		INT(11) 		DEFAULT NULL 	COMMENT 'Código del módulo origen de la información',
   COD_TITULO 		INT(11) 		DEFAULT NULL 	COMMENT 'Código del título contable',
   COD_CAPITULO 	INT(11) 		DEFAULT NULL 	COMMENT 'Código del capítulo contable',
   COD_PLAZO 		INT(11) 		DEFAULT NULL 	COMMENT 'Código del plazo asociado al saldo',
   COD_GRUPO 		INT(11) 		DEFAULT NULL 	COMMENT 'Código de agrupación financiera o regulatoria',
   MTO_SALDO_MO 	DECIMAL(17,2) 	DEFAULT NULL 	COMMENT 'Monto del saldo en moneda original',
   MTO_SALDO_ME 	DECIMAL(17,2) 	DEFAULT NULL 	COMMENT 'Monto del saldo en moneda extranjera',
   MTO_SALDO_MN 	DECIMAL(17,2) 	DEFAULT NULL 	COMMENT 'Monto del saldo en moneda nacional',
   MTO_SALDO_MES_MN     DECIMAL(17,2)   DEFAULT NULL 	COMMENT 'Promedio de saldo moneda original',
   MTO_SALDO_MES_ME		DECIMAL(17,2)   DEFAULT NULL 	COMMENT 'Variacion de saldo con respecto al  mes anterior de moneda original',
   MTO_SALDO_MES_MO     DECIMAL(17,2)   DEFAULT NULL 	COMMENT 'Promedio de saldo moneda extrangera',
   MTO_AVG_MES_MO		DECIMAL(17,2)   DEFAULT NULL 	COMMENT 'Variacion de saldo con respecto al  mes anterior de moneda extrangera',
   MTO_AVG_MES_ME     DECIMAL(17,2)   DEFAULT NULL 	COMMENT 'Promedio de saldo moneda nacional',
   MTO_AVG_MES_MN		DECIMAL(17,2)   DEFAULT NULL 	COMMENT 'Variacion de saldo con respecto al  mes anterior de moneda nacional',
   FUENTE 			VARCHAR(250) 	DEFAULT 'BANTOTAL' COMMENT 'Sistema origen de la información',
   FEC_CARGA 		DATETIME 		DEFAULT NULL 	COMMENT 'Fecha y hora de carga del registro',
   BATCH_ID 		VARCHAR(25) 	DEFAULT NULL 	COMMENT 'Identificador del proceso de carga',
   SHARD KEY (FECHA_PROCESO,COD_EMPRESA, COD_SUCURSAL, COD_RUBRO, COD_MONEDA, COD_PAPEL, COD_MODULO,COD_TITULO, COD_CAPITULO, COD_PLAZO, COD_GRUPO ),
   CONSTRAINT UK_BDS_SALDOS_DIARIOS_CONSOLIDADOS_01 UNIQUE (FECHA_PROCESO, COD_EMPRESA, COD_SUCURSAL, COD_RUBRO, COD_MONEDA, COD_PAPEL, COD_MODULO,COD_TITULO, COD_CAPITULO, COD_PLAZO, COD_GRUPO)
);