CREATE TABLE BDS_SALDOS_OPERATIVOS (
   ID_OPERACION_CIERRE varchar(200) NOT NULL COMMENT 'Identificador único de la operación financiera dentro del sistema origen. Permite individualizar y rastrear cada operación registrada.',
   FECHA_PROCESO date DEFAULT NULL COMMENT 'Fecha de procesamiento o cierre sobre la cual se calculan y consolidan los saldos operativos.',
   COD_EMPRESA int(11) DEFAULT NULL COMMENT 'Código de la empresa o entidad financiera responsable de la operación.',
   COD_SUCURSAL int(11) DEFAULT NULL COMMENT 'Código de la oficina, agencia o sucursal donde se originó o administra la operación.',
   COD_MONEDA int(11) DEFAULT NULL COMMENT 'Código de moneda de la operación según el catálogo corporativo de monedas.',
   COD_PAPEL int(11) DEFAULT NULL COMMENT 'Código que identifica el tipo de papel financiero, instrumento o clasificación contable asociada.',
   NUM_CUENTA_BT int(11) DEFAULT NULL COMMENT 'Número de cuenta contable o cuenta de balance utilizada para registrar la operación.',
   COD_OPERACION int(11) DEFAULT NULL COMMENT 'Código interno que identifica la operación financiera dentro de la entidad.',
   COD_TIPO_OPERACION int(11) DEFAULT NULL COMMENT 'Código que clasifica la operación según su naturaleza financiera o comercial.',
   COD_MODULO int(11) DEFAULT NULL COMMENT 'Código del módulo de negocio o sistema fuente responsable del registro de la operación.',
   FEC_VALOR date DEFAULT NULL COMMENT 'Fecha valor aplicada a la operación para efectos financieros y de cálculo de intereses.',
   IND_CATEGORIA_RIESGO varchar(15) DEFAULT NULL COMMENT 'Indicador de la categoría de riesgo asignada a la operación conforme a normativa y políticas internas.',
   COD_ACTI_BCO_CENTRAL bigint(20) DEFAULT NULL COMMENT 'Código de actividad económica reportado al Banco Central o utilizado para clasificación regulatoria.',
   COD_PRODUCTO int(11) DEFAULT NULL COMMENT 'Código del producto financiero asociado a la operación.',
   TOTAL_MTO_SALDO_ORIGEN decimal(17,2) DEFAULT NULL COMMENT 'Saldo de la operación expresado en la moneda de origen.',
   TOTAL_SALDO_MN decimal(39,2) DEFAULT NULL COMMENT 'Saldo total de la operación convertido y consolidado en moneda nacional.',
   TOTAL_SALDO_ME decimal(39,2) DEFAULT NULL COMMENT 'Saldo total de la operación consolidado en moneda extranjera.',
   TOTAL_SALDO_MO decimal(39,2) DEFAULT NULL COMMENT 'Saldo total de la operación expresado en la moneda original de contratación.',
   TOTAL_MTO_INTERES decimal(17,2) DEFAULT NULL COMMENT 'Monto acumulado de intereses asociados a la operación a la fecha de proceso.',
   TOTAL_MTO_PREVISIONES decimal(17,2) DEFAULT NULL COMMENT 'Monto de provisiones o previsiones constituidas para la operación.',
   TOTAL_AVG_SALDO_ORIGEN decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio de la operación en moneda de origen durante el período evaluado.',
   TOTAL_AVG_SALDO_MN decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio de la operación en moneda nacional durante el período evaluado.',
   TOTAL_AVG_SALDO_ME decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio de la operación en moneda extranjera durante el período evaluado.',
   TOTAL_AVG_SALDO_MO decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio de la operación en moneda original durante el período evaluado.',
   TOTAL_AVG_SALDO_ORIGEN_LABORABLES decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio calculado considerando únicamente días laborables en moneda de origen.',
   TOTAL_AVG_SALDO_MN_LABORABLES decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio calculado considerando únicamente días laborables en moneda nacional.',
   TOTAL_AVG_SALDO_ME_LABORABLES decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio calculado considerando únicamente días laborables en moneda extranjera.',
   TOTAL_AVG_SALDO_MO_LABORABLES decimal(17,4) DEFAULT NULL COMMENT 'Saldo promedio calculado considerando únicamente días laborables en moneda original.',
   TOTAL_MTO_SALDO_VIGENTE_MO decimal(21,2) DEFAULT NULL COMMENT 'Monto del saldo vigente de la operación en moneda original.',
   TOTAL_MTO_SALDO_RESTRUCTURADO_MO decimal(21,2) DEFAULT NULL COMMENT 'Monto correspondiente al saldo de operaciones reestructuradas en moneda original.',
   TOTAL_MTO_SALDO_REFINANCIADO_MO decimal(21,2) DEFAULT NULL COMMENT 'Monto correspondiente al saldo de operaciones refinanciadas en moneda original.',
   TOTAL_MTO_SALDO_VENCIDO_MO decimal(21,2) DEFAULT NULL COMMENT 'Monto del saldo vencido de la operación en moneda original.',
   TOTAL_MTO_SALDO_JUDIAL_MO decimal(21,2) DEFAULT NULL COMMENT 'Monto del saldo en cobranza judicial o proceso legal en moneda original.',
   FUENTE varchar(250) DEFAULT NULL COMMENT 'Nombre del sistema, proceso o fuente de datos desde donde se obtuvo la información.',
   FECHA_CARGA datetime DEFAULT NULL COMMENT 'Fecha y hora en que el registro fue cargado al repositorio analítico.',
   BATCH_ID varchar(25) DEFAULT NULL COMMENT 'Identificador único del lote o ejecución ETL que generó la carga del registro.',
   CONSTRAINT UK_SP_BDS_SALDOS_OPERATIVOS UNIQUE (ID_OPERACION_CIERRE, FECHA_PROCESO),
   SHARD KEY (ID_OPERACION_CIERRE, FECHA_PROCESO)
);