CREATE TABLE BDS_CODIGO_RUBRO_SBS(
	COD_RUBRO_SBS	 	VARCHAR(20)  	NOT NULL  		COMMENT 'Codigo de Rubro segun SBS',
	DES_RUBRO			VARCHAR(200) 	DEFAULT NULL  	COMMENT 'Descripcion de codigo de SBS',
	FLG_ANALISIS		VARCHAR(1) 		DEFAULT NULL	COMMENT 'Nivel maximo de profundidad de digitos de SBS',
	DES_NATURALEZA		VARCHAR(50) 	DEFAULT NULL	COMMENT 'Clasificacion segun la SBS',
	GRU_CONTABLE 		VARCHAR(100) 	DEFAULT NULL	COMMENT 'Grupo contable clasificado segun USUARIO',
	DES_COMPONENTE		VARCHAR(50) 	DEFAULT NULL	COMMENT 'Componente clasificación INTerna',	
	DES_DOMINIO			VARCHAR(50) 	DEFAULT NULL	COMMENT '',	
	TIP_SALDO			VARCHAR(50) 	DEFAULT NULL	COMMENT '',	
	TIP_PRESTAMO 		VARCHAR(50) 	DEFAULT NULL	COMMENT '',	
	SBS_NIVEL			BIGINT 			DEFAULT NULL	COMMENT 'Cnatidad de digitos que indica el grado de especificación',
	SHARD KEY(COD_RUBRO_SBS),
	CONSTRAINT UK_BDS_CODIGO_RUBRO_SBS UNIQUE(COD_RUBRO_SBS)
);